#!/usr/bin/env python3
"""Generate batch64: 12 新词根 + 14 补词。

新根（各族在考研词表内均有 3 个以上成员）：
  jungere（接合）    join / joint / junction
  jus（法权）        judge / jury / justice / justify
  ire（行走）        exit / initial / initiate / issue
  haerere（黏住）    coherent / cohesive / inherent / hesitate
  fendere（击打）    defend / defence / fence
  frons（额面）      front / frontier / confront
  vadere（迈步）     invade / invasion / evade
  fari（说）         fable / fabulous / infant
  flos（花）         flower / flour / flourish
  heres（承继人）    heir / heritage / inherit
  jocus（戏言）      joke / jewel / jewelry
  dran（做、演）     drama / dramatic / drastic

补进已建模根（含一处纠正）：
  fac ← fashion / fax / feasible
      子代理报作新根 facere，但 fac 的 origin 就写「拉丁语 facere」，同一个根
  habere ← due / duty / endeavor      cura ← insure     gravis ← grief
  ars ← inertia    credere ← grant    fundere ← futile
  graphein ← glamor    klinein ← incline    vert ← divorce

【fari 与已建 fatum 的关系，词根条目里写明】
fatum 是 fari 的过去分词中性形（「所说定之事」），第六十一批先建。
本批的 fari 是那个被派生的本体：fable ← fabula ← fari，
infant ← infans（in-＋fari 的现在分词，不会说话的）。
二者同源分支不同，照 dare 与 edere-publish/tradere 的先例并立而非合并。
（若日后要合并成一个 6 词族，需迁移 fate/fatal/fairy 三词，另作一步。）

【ire 与 circulus 的交叉，一并记下】
第六十批把 circuit 收进 circulus，并在词条注明其主根实为 ire。
本批 ire 建根后，circuit 严格说更该归 ire；但它与 circle/circular/circus
的「绕回原点」意象更贴，暂留 circulus 不动，此处记录以备日后复核。

写法：W() 定参函数。Q12/Q1 自检与自环断言均在生成期。
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "ai_pipeline" / "batch64.json"


def W(wid, rid, pos, ph, logic, origin, native, concept, image, zh, ex, syn, ant, rel, exp, hint):
    return {
        "id": wid, "word": wid, "pos": pos, "phonetic": ph,
        "decomposable": "root", "root_ids": [rid],
        "root_logic": logic, "origin": origin,
        "native_definition": native, "core_concept": concept,
        "core_image": image, "chinese": zh, "examples": ex,
        "synonyms": syn, "antonyms": ant, "related": rel,
        "semantic_expansions": exp, "recall_hint": hint,
    }


families = []
additions = []

# ---------- jungere（接合）----------
families.append({
    "root": {
        "id": "jungere", "root": "jungere", "variants": ["join", "junct", "jug"],
        "origin": "拉丁语 jungere（把两物套到一处），过去分词 junctus；"
                  "jugum（牛轭）同根——两头牛套进同一副轭，是这一族的本象",
        "core_concept": "two things set into one yoke so they move as one / 两物套进同一副轭，从此一起动",
        "core_image": "一副木轭卡在两头牛的颈上，一头往前，另一头跟着走",
        "english_definition": "to yoke, join together",
    },
    "concept": {
        "id": "concept-jungere-yoke", "concept": "two things set into one yoke so they move as one",
        "chinese": "套在一处", "core_image": "木轭卡在两头牛颈上，一头往前另一头跟着走",
        "root_ids": ["jungere"], "word_ids": [],
    },
    "domain": "domain-hold",
    "words": [
        W("join", "jungere", "verb", "/dʒɔɪn/",
          "jungere（套到一处）→ 把两边接上，或自己并进去",
          "古法语 joindre ← 拉丁语 jungere（接合）",
          "to connect two things; to become a member of a group",
          "bringing two ends together until they hold as one – 把两头凑到一处，直到它们成一体",
          "两截管子对上口，箍一紧就再拔不开",
          ["连接", "加入", "接合"],
          ["Join the two wires together.", "She joined the club last spring."],
          ["connect", "unite"], ["separate", "split"],
          ["joint", "junction"],
          ["连接/接合：把两头凑到一处使成一体", "加入：把自己并进那一群里"],
          "jungere（套到一处）→ 把两边接上"),
        W("joint", "jungere", "noun", "/dʒɔɪnt/",
          "junctus（已接合的）→ 两段相接的那一处 → 关节、接头",
          "古法语 jointe ← 拉丁语 junctus（jungere 的过去分词）",
          "a place where two parts meet and can move; shared between two",
          "the spot where two pieces meet and still bend – 两段相接、又还能弯的那一处",
          "两根骨头搭在一处，中间那点能屈能伸",
          ["关节", "接头", "共同的"],
          ["He injured his knee joint.", "They made a joint decision."],
          ["junction", "shared"], [],
          ["join", "junction"],
          ["关节/接头：两段相接又能活动的那一处", "共同的：两方套在同一副轭里、一起承担"],
          "junctus（已接合）→ 两段相接的那一处"),
        W("junction", "jungere", "noun", "/ˈdʒʌŋkʃn/",
          "junct（接合）+ -ion → 几条道接到一处的那个点 → 交汇处",
          "拉丁语 junctio（接合）← jungere（接合）",
          "a place where roads or railway lines meet",
          "the point several ways run into and become one – 几条路跑到一处、并成一条的那个点",
          "三条道跑到一处并成一条，中间立着一根杆",
          ["交汇处", "路口", "枢纽"],
          ["Turn left at the next junction.", "The junction was closed for repairs."],
          ["meeting", "corner"], [],
          ["join", "joint"],
          ["交汇处/路口：几条道接到一处的那个点", "枢纽：多条线路在此并接的要地"],
          "junct（接合）+ -ion → 几条道接到一处的点"),
    ],
})

# ---------- jus（法权）----------
families.append({
    "root": {
        "id": "jus", "root": "jus", "variants": ["jud", "jur", "just"],
        "origin": "拉丁语 jus（属格 juris：法、权利）；judex 是 jus＋dicere（宣法者），"
                  "jurare 是「按法起誓」，justus 是「合于法的」",
        "core_concept": "the standard by which right is measured / 衡量对错所依的那把准",
        "core_image": "一杆秤立在中间，两边各放一份，看它往哪边偏",
        "english_definition": "law, right, what is due",
    },
    "concept": {
        "id": "concept-jus-law", "concept": "the standard by which right is measured",
        "chinese": "衡量对错之准", "core_image": "一杆秤立在中间，两边各放一份，看它往哪边偏",
        "root_ids": ["jus"], "word_ids": [],
    },
    "domain": "domain-perceive",
    "words": [
        W("judge", "jus", "verb", "/dʒʌdʒ/",
          "jus（法）+ dicere（说）→ judex（宣法的人）→ 依准断定",
          "古法语 juger ← 拉丁语 judicare ← judex（法官）← jus（法）＋dicere（说）",
          "to form an opinion after weighing evidence; a person who decides in court",
          "the one who reads the scale and says which way it went – 看着秤，说出它偏向哪边的那个",
          "两边的说法都听完，他抬头说出偏向哪一边",
          ["判断", "评判", "法官"],
          ["Do not judge by appearance.", "The judge dismissed the case."],
          ["assess", "magistrate"], [],
          ["justice", "jury"],
          ["判断/评判：依准衡量后说出结论", "法官：受命做此事的那个人"],
          "jus（法）+ dicere（说）→ 依准断定的人"),
        W("jury", "jus", "noun", "/ˈdʒʊəri/",
          "jurare（按法起誓）→ 起过誓来断案的那一组人",
          "盎格鲁法语 juree ← 拉丁语 jurata（起誓者）← jurare（起誓）← jus（法）",
          "a group of people who decide a verdict in court",
          "the several sworn in to read the scale together – 一齐起过誓、共同看秤的那几个人",
          "十二个人挨着坐一排，手按在书上说完同一句话",
          ["陪审团", "评审团"],
          ["The jury reached a verdict.", "She served on a jury last year."],
          ["panel", "board"], [],
          ["judge", "justice"],
          ["陪审团/评审团：起誓后共同评断的那一组人"],
          "jurare（按法起誓）→ 起誓断案的那组人"),
        W("justice", "jus", "noun", "/ˈdʒʌstɪs/",
          "just（合于法）+ -ice → 该给谁的就给谁 → 公正",
          "古法语 justice ← 拉丁语 justitia（公正）← justus（合法的）← jus（法）",
          "fair treatment; the system of law",
          "the scale coming to rest level, neither side favoured – 秤停在正中，两边谁也不占便宜",
          "两份东西各放一边，指针不偏不倚停在中线",
          ["公正", "司法", "正义"],
          ["She fought for justice.", "The case went to the justice system."],
          ["fairness", "law"], ["unfair"],
          ["judge", "justify"],
          ["公正/正义：秤停在正中、该给谁给谁", "司法：把这套准则落实下来的那一整套"],
          "just（合于法）+ -ice → 该给谁就给谁"),
        W("justify", "jus", "verb", "/ˈdʒʌstɪfaɪ/",
          "just（合于法）+ -ify（使…）→ 说明它站得住 → 证明正当",
          "古法语 justifier ← 晚期拉丁语 justificare ← justus（合法的）＋facere（做）",
          "to show that something is right or reasonable",
          "putting weight on your side until the scale tips your way – 往自己这边添分量，直到秤偏过来",
          "他把一件件依据摆到自己那盘里，秤慢慢压了过去",
          ["证明正当", "辩解", "为…提供理由"],
          ["Can you justify that cost?", "Nothing justifies such cruelty."],
          ["defend", "warrant"], [],
          ["justice", "judge"],
          ["证明正当/为…提供理由：添够分量使秤偏向自己", "辩解：为已做之事补上这份分量"],
          "just（合于法）+ -ify → 说明它站得住"),
    ],
})

# ---------- ire（行走）----------
families.append({
    "root": {
        "id": "ire", "root": "ire", "variants": ["it", "iti", "issu"],
        "origin": "拉丁语 ire（去、行走），过去分词 itum；exire（出去）、initium（进入之始）、"
                  "exitus（出口）皆由此出",
        "core_concept": "setting off and passing through / 起脚往前，一路走过去",
        "core_image": "门槛一跨，脚已经落在门外那一侧",
        "english_definition": "to go",
    },
    "concept": {
        "id": "concept-ire-go", "concept": "setting off and passing through",
        "chinese": "起脚而行", "core_image": "门槛一跨，脚已经落在门外那一侧",
        "root_ids": ["ire"], "word_ids": [],
    },
    "domain": "domain-transfer",
    "words": [
        W("exit", "ire", "noun", "/ˈeksɪt/",
          "ex-（出）+ it（ire 行走）→ 走出去的那个口",
          "拉丁语 exitus（出去、出口）← exire（出去）← ex＋ire（行走）",
          "a way out of a place; the act of leaving",
          "the gap you step through on the way out – 往外走时跨过的那个口",
          "绿灯亮着的那扇门后头是台阶，人一个个跨出去",
          ["出口", "退场", "离开"],
          ["The exit is at the back.", "He made a quiet exit."],
          ["door", "departure"], ["entrance"],
          ["initial", "issue"],
          ["出口：往外走时跨过的那个口", "退场/离开：跨出去这个动作本身"],
          "ex-（出）+ it（行走）→ 走出去的那个口"),
        W("initial", "ire", "adjective", "/ɪˈnɪʃl/",
          "in-（进入）+ it（行走）+ -al → initium（迈进的第一步）→ 最初的",
          "拉丁语 initialis（起头的）← initium（开始）← inire（进入）← in＋ire（行走）",
          "existing at the beginning; the first letter of a name",
          "the first foot set down inside the door – 进门后落下的第一只脚",
          "刚跨进来那一步印在灰上，后面的脚印都在它前头",
          ["最初的", "开头的", "首字母"],
          ["My initial reaction was surprise.", "Sign with your initials here."],
          ["first", "opening"], ["final"],
          ["initiate", "exit"],
          ["最初的/开头的：进门后落下的第一只脚", "首字母：名字最前头那一个字"],
          "in-（进入）+ it（行走）→ 迈进的第一步"),
        W("initiate", "ire", "verb", "/ɪˈnɪʃieɪt/",
          "initium（第一步）+ -ate（使…）→ 走出第一步 → 发起",
          "拉丁语 initiare（开始、引入）← initium ← inire（进入）← in＋ire",
          "to cause something to begin; to admit someone into a group",
          "taking the one step that starts the rest moving – 迈出那一步，后面的才跟着动",
          "他先走了一步，原地站着的人这才跟上",
          ["发起", "开始", "使入会"],
          ["They initiated a new program.", "He was initiated into the order."],
          ["begin", "launch"], ["conclude"],
          ["initial", "exit"],
          ["发起/开始：迈出那第一步使其余跟着动", "使入会：引某人跨进那个圈子"],
          "initium（第一步）+ -ate → 走出第一步"),
        W("issue", "ire", "noun", "/ˈɪʃuː/",
          "ex-（出）+ issue（ire 行走）→ 走出来的那一批 → 发行；引申为待处理之事",
          "古法语 issue（出去、结果）← 拉丁语 exire（出去）← ex＋ire（行走）",
          "an important topic; a set of copies published at one time; to send out",
          "what comes walking out of the door, batch by batch – 一批批从门里走出来的那些",
          "印好的一摞从后门一批批运出来，封面日期都一样",
          ["问题", "议题", "期号", "发行"],
          ["This is a serious issue.", "The magazine issues monthly."],
          ["matter", "edition"], [],
          ["exit", "initial"],
          ["问题/议题：摆到面前待处理的那一桩", "期号/发行：一批批出门的那些印本"],
          "ex-（出）+ issue（行走）→ 走出来的那一批"),
    ],
})

# ---------- haerere（黏住）----------
families.append({
    "root": {
        "id": "haerere", "root": "haerere", "variants": ["her", "hes", "hae"],
        "origin": "拉丁语 haerere（黏住、卡住不动），过去分词 haesus；"
                  "黏得牢即「连贯」，卡住不动即「犹疑」，两支同出一象",
        "core_concept": "sticking fast so it will not come loose / 黏牢在那儿，撕不开也动不了",
        "core_image": "两张纸沾在一处，手一撕就带下毛边，谁也不肯干净分开",
        "english_definition": "to stick, cling, be fixed",
    },
    "concept": {
        "id": "concept-haerere-stick", "concept": "sticking fast so it will not come loose",
        "chinese": "黏牢难分", "core_image": "两张纸沾在一处，一撕就带毛边，谁也不肯干净分开",
        "root_ids": ["haerere"], "word_ids": [],
    },
    "domain": "domain-hold",
    "words": [
        W("coherent", "haerere", "adjective", "/kəʊˈhɪərənt/",
          "co-（一起）+ her（黏住）+ -ent → 各部分黏成一体、说得通的",
          "拉丁语 cohaerens（连在一起的）← cohaerere ← com＋haerere（黏住）",
          "logically connected and easy to follow",
          "the parts stuck together so tightly the whole holds – 各部分黏得够牢，整体拎起来不散",
          "几段话前后咬着，抽掉哪一段后面都接不上",
          ["连贯的", "条理清楚的"],
          ["She gave a coherent account.", "The argument is not coherent."],
          ["logical", "consistent"], ["muddled"],
          ["cohesive", "inherent"],
          ["连贯的/条理清楚的：各部分黏成一体、拎起来不散"],
          "co-（一起）+ her（黏住）→ 各部分黏成一体"),
        W("cohesive", "haerere", "adjective", "/kəʊˈhiːsɪv/",
          "co-（一起）+ hes（黏住）+ -ive → 能把彼此黏住的",
          "英语 cohesive，来自拉丁语 cohaesus（cohaerere 的过去分词）← haerere",
          "sticking together well; forming a united whole",
          "what makes the pieces hold to one another – 使各块相互黏着的那份力",
          "湿沙攥成一团松手不散，干沙一松就漏下去",
          ["有黏性的", "团结的"],
          ["They are a cohesive team.", "Wet clay is more cohesive."],
          ["sticky", "firm"], ["loose"],
          ["coherent", "inherent"],
          ["有黏性的：能把彼此黏住的", "团结的：一群人同样相互黏着不散"],
          "co-（一起）+ hes（黏住）+ -ive → 能相互黏住的"),
        W("inherent", "haerere", "adjective", "/ɪnˈhɪərənt/",
          "in-（在内）+ her（黏住）+ -ent → 黏在里头拿不掉的 → 固有的",
          "拉丁语 inhaerens（附着于内的）← inhaerere ← in＋haerere（黏住）",
          "existing as a natural and permanent part of something",
          "stuck so deep inside that removing it would break the thing – 黏在里头，要取出来就得把那东西拆了",
          "花纹是烧进瓷胎里的，擦不掉也磨不去",
          ["固有的", "内在的", "天生的"],
          ["Risk is inherent in the job.", "It has an inherent weakness."],
          ["intrinsic", "natural"], ["external"],
          ["coherent", "hesitate"],
          ["固有的/内在的/天生的：黏在里头取不出来的那部分"],
          "in-（在内）+ her（黏住）→ 黏在里头拿不掉"),
        W("hesitate", "haerere", "verb", "/ˈhezɪteɪt/",
          "haes（卡住不动）+ -itate（反复）→ 反复卡在那儿 → 迟疑",
          "拉丁语 haesitare（卡住、结巴）← haerere（黏住、卡住）的反复体",
          "to pause before doing something because of doubt",
          "the foot that lifts and comes back down in the same spot – 脚抬起来又落回原处，没往前挪",
          "他手伸到一半停住，收回来又伸出去",
          ["犹豫", "迟疑"],
          ["She hesitated before answering.", "Do not hesitate to ask."],
          ["pause", "delay"], ["decide"],
          ["inherent", "coherent"],
          ["犹豫/迟疑：脚抬起又落回原处，反复卡在那儿"],
          "haes（卡住）+ -itate（反复）→ 反复卡在那儿"),
    ],
})

# ---------- fendere（击打）----------
families.append({
    "root": {
        "id": "fendere", "root": "fendere", "variants": ["fend", "fenc", "fens"],
        "origin": "拉丁语 -fendere（击、挡），只见于复合词：defendere（挡开）、"
                  "offendere（撞上去）；英语 fence 是 defence 的截短",
        "core_concept": "striking to keep a thing off / 挥出去一击，把来的挡在外头",
        "core_image": "手臂横着一挡，来的那一下被架在外圈",
        "english_definition": "to strike, ward off",
    },
    "concept": {
        "id": "concept-fendere-ward-off", "concept": "striking to keep a thing off",
        "chinese": "挥击相挡", "core_image": "手臂横着一挡，来的那一下被架在外圈",
        "root_ids": ["fendere"], "word_ids": [],
    },
    "domain": "domain-force",
    "words": [
        W("defend", "fendere", "verb", "/dɪˈfend/",
          "de-（离开）+ fend（击）→ 把来的击开、使它离远 → 防御",
          "古法语 defendre ← 拉丁语 defendere（挡开、保护）← de＋fendere（击）",
          "to protect from attack; to argue in support of",
          "the arm put up so the blow lands somewhere else – 手臂架上去，那一下就落到别处",
          "他抬臂一格，砸下来的那下偏到了肩外",
          ["保卫", "防御", "辩护"],
          ["They defended the city for weeks.", "She defended her decision."],
          ["protect", "guard"], ["attack"],
          ["defence", "fence"],
          ["保卫/防御：把来的击开使其落到别处", "辩护：同样是把冲自己来的话挡开"],
          "de-（离开）+ fend（击）→ 把来的击开"),
        W("defence", "fendere", "noun", "/dɪˈfens/",
          "defend（挡开）+ -ce → 挡这件事，及用来挡的那一套",
          "古法语 defense ← 拉丁语 defensa ← defendere（挡开）← de＋fendere",
          "the act of protecting; something that protects",
          "whatever is put between you and the blow – 架在自己与那一下之间的东西",
          "土墙、壕沟、拒马一层层排在前头",
          ["防御", "防务", "辩护"],
          ["The country spends much on defence.", "He spoke in his own defence."],
          ["protection", "shield"], ["attack"],
          ["defend", "fence"],
          ["防御/防务：挡这件事及用来挡的那一套", "辩护：法庭上替自己挡的那番话"],
          "defend（挡开）+ -ce → 挡这件事及所用之物"),
        W("fence", "fendere", "noun", "/fens/",
          "defence 的截短 → 拦在四周挡人畜的那道栅",
          "中古英语 fens，defence 的截短形 ← 拉丁语 defendere（挡开）",
          "a barrier of wood or wire around a piece of land",
          "the line of stakes that keeps what is outside outside – 一排桩子把外头的挡在外头",
          "一排木桩钉进土里，中间拉着铁丝，牛走到那儿就停",
          ["篱笆", "栅栏", "围栏"],
          ["They built a fence around the yard.", "The horse jumped the fence."],
          ["barrier", "railing"], [],
          ["defend", "defence"],
          ["篱笆/栅栏/围栏：拦在四周、把外头挡在外头的那道"],
          "defence 截短 → 拦在四周挡人畜的那道栅"),
    ],
})

# ---------- frons（额面）----------
families.append({
    "root": {
        "id": "frons", "root": "frons", "variants": ["front", "fronti"],
        "origin": "拉丁语 frons（属格 frontis：额头、正面）；额头是人朝前的那一面，"
                  "故引申为凡物的正面与前缘",
        "core_concept": "the face a thing turns forward / 一物朝前的那一面",
        "core_image": "两人对面站着，额头正对额头，谁也没侧过身",
        "english_definition": "forehead, front",
    },
    "concept": {
        "id": "concept-frons-forward-face", "concept": "the face a thing turns forward",
        "chinese": "朝前那一面", "core_image": "两人对面站着，额头正对额头，谁也没侧身",
        "root_ids": ["frons"], "word_ids": [],
    },
    "domain": "domain-shape",
    "words": [
        W("front", "frons", "noun", "/frʌnt/",
          "frons（额头）→ 朝前的那一面 → 前部、正面",
          "古法语 front（额、正面）← 拉丁语 frons（额头）",
          "the side that faces forward; the most forward part",
          "the face that meets you first as you come up – 你走近时先碰到的那一面",
          "屋子朝街那一面开着窗，背面只有一道墙",
          ["前面", "正面", "前线"],
          ["Sit at the front of the bus.", "Troops moved up to the front."],
          ["face", "head"], ["back", "rear"],
          ["frontier", "confront"],
          ["前面/正面：朝前、先碰到的那一面", "前线：两军相对时朝前的那一面"],
          "frons（额头）→ 朝前的那一面"),
        W("frontier", "frons", "noun", "/ˈfrʌntɪə(r)/",
          "front（正面）+ -ier → 一国朝外那条边 → 边境；引申为未开之域",
          "古法语 frontiere（前沿）← front ← 拉丁语 frons（额头、正面）",
          "the border between two countries; the edge of what is known",
          "the outermost line a land turns toward the world – 一片地朝外顶着的那条最外的线",
          "界桩一路排到山脊，过了那道线就是别处",
          ["边境", "边疆", "前沿"],
          ["They crossed the frontier at night.", "It is a new frontier in medicine."],
          ["border", "boundary"], [],
          ["front", "confront"],
          ["边境/边疆：一国朝外顶着的那条最外线", "前沿：知识或技术顶到的那条边"],
          "front（正面）+ -ier → 朝外顶着的那条边"),
        W("confront", "frons", "verb", "/kənˈfrʌnt/",
          "con-（相对）+ front（额面）→ 额头对额头 → 正面相对",
          "法语 confronter ← 中世纪拉丁语 confrontare ← com＋frons（额头）",
          "to face someone or something difficult directly",
          "turning to put your forehead against the other's – 转过身把自己的额头对上对方的",
          "他没有绕开，转过身直接站到那人跟前",
          ["面对", "对抗", "使对质"],
          ["She confronted him about the lie.", "We must confront the problem."],
          ["face", "challenge"], ["avoid"],
          ["front", "frontier"],
          ["面对/对抗：转身把额头对上对方，不绕开", "使对质：把两方拉到面对面"],
          "con-（相对）+ front（额面）→ 额头对额头"),
    ],
})

# ---------- vadere（迈步）----------
families.append({
    "root": {
        "id": "vadere", "root": "vadere", "variants": ["vad", "vas"],
        "origin": "拉丁语 vadere（迈开步子走、涉水而过），过去分词 vasus；"
                  "invadere 是「迈进别人的地界」，evadere 是「迈出去脱身」",
        "core_concept": "striding across a line one is not meant to cross / 大步迈过那条本不该跨的线",
        "core_image": "一脚跨过界桩，另一只脚跟着落在别人的地里",
        "english_definition": "to go, stride, wade",
    },
    "concept": {
        "id": "concept-vadere-stride", "concept": "striding across a line one is not meant to cross",
        "chinese": "跨界迈入", "core_image": "一脚跨过界桩，另一只脚跟着落在别人地里",
        "root_ids": ["vadere"], "word_ids": [],
    },
    "domain": "domain-transfer",
    "words": [
        W("invade", "vadere", "verb", "/ɪnˈveɪd/",
          "in-（进入）+ vade（迈步）→ 迈进别人的地界 → 侵入",
          "拉丁语 invadere（侵入）← in＋vadere（迈步而行）",
          "to enter a place by force; to crowd into somewhere",
          "the foot coming down inside a line it had no right to cross – 脚落在本不该越过的那条线里侧",
          "界桩还立在那儿，一队人已经踩进了桩子里边",
          ["侵略", "侵入", "涌入"],
          ["The army invaded at dawn.", "Tourists invade the town each July."],
          ["attack", "occupy"], ["retreat"],
          ["invasion", "evade"],
          ["侵略/侵入：迈进本不该进的地界", "涌入：大批人同样跨进来占满"],
          "in-（进入）+ vade（迈步）→ 迈进别人地界"),
        W("invasion", "vadere", "noun", "/ɪnˈveɪʒn/",
          "invade（侵入）+ -sion → 侵入这件事",
          "拉丁语 invasio ← invadere（侵入）← in＋vadere",
          "an act of entering by force; an unwelcome intrusion",
          "the whole of that crossing, once it has happened – 跨进来这件事整个算下来",
          "第二天清早，界内已经全是别处来的脚印",
          ["入侵", "侵犯"],
          ["The invasion began in spring.", "It was an invasion of privacy."],
          ["attack", "raid"], [],
          ["invade", "evade"],
          ["入侵/侵犯：迈进本不该进之处这件事"],
          "invade（侵入）+ -sion → 侵入这件事"),
        W("evade", "vadere", "verb", "/ɪˈveɪd/",
          "e-（ex- 出）+ vade（迈步）→ 迈出去脱身 → 躲开",
          "拉丁语 evadere（逃出）← ex＋vadere（迈步而行）",
          "to escape or avoid something, often by cleverness",
          "stepping out through the gap before the hand closes – 手合上之前先迈出那道缝",
          "追到墙角却没人，只有一扇半开的小门",
          ["逃避", "回避", "躲开"],
          ["He evaded the question.", "She evaded capture for months."],
          ["escape", "avoid"], ["confront"],
          ["invade", "invasion"],
          ["逃避/回避：手合上之前先迈出那道缝", "躲开：同一动作用在具体的追捕上"],
          "e-（出）+ vade（迈步）→ 迈出去脱身"),
    ],
})

# ---------- fari（说）----------
families.append({
    "root": {
        "id": "fari", "root": "fari", "variants": ["fab", "fan", "fess"],
        "origin": "拉丁语 fari（说、开口），现在分词 fans、过去分词中性 fatum。"
                  "第六十一批先建的 fatum（说定之数）正是它的过去分词；"
                  "本根是被派生的本体，二者同源分支不同，照 dare 与 edere-publish/tradere 的先例并立",
        "core_concept": "opening the mouth and letting words out / 开口，把话放出来",
        "core_image": "嘴唇一动，话就出去了，收不回来",
        "english_definition": "to speak, utter",
    },
    "concept": {
        "id": "concept-fari-speak", "concept": "opening the mouth and letting words out",
        "chinese": "开口出言", "core_image": "嘴唇一动，话就出去了，收不回来",
        "root_ids": ["fari"], "word_ids": [],
    },
    "domain": "domain-perceive",
    "words": [
        W("fable", "fari", "noun", "/ˈfeɪbl/",
          "fabula（讲出来的话）← fari（说）→ 讲给人听的那种短故事",
          "古法语 fable ← 拉丁语 fabula（谈话、故事）← fari（说）",
          "a short story with a moral, often about animals",
          "the tale that exists only in the telling – 只靠口说才存在的那个故事",
          "老人一开口讲那只狐狸，孩子们就不出声了",
          ["寓言", "传说", "虚构之事"],
          ["He read the fable aloud.", "That story is pure fable."],
          ["tale", "legend"], ["fact"],
          ["fabulous", "infant"],
          ["寓言/传说：靠口说流传的那种短故事", "虚构之事：因此指不实之说"],
          "fabula（讲出来的话）← fari（说）→ 口说的故事"),
        W("fabulous", "fari", "adjective", "/ˈfæbjələs/",
          "fabula（故事）+ -ous → 像故事里那样的 → 惊人的、极好的",
          "拉丁语 fabulosus（传说中的）← fabula（故事）← fari（说）",
          "extremely good; so great as to seem made up",
          "the kind of thing you would only expect to hear in a tale – 只该在故事里听到的那种",
          "端上来那一桌，客人先说了句「这哪像真的」",
          ["极好的", "惊人的", "传说中的"],
          ["The meal was fabulous.", "He has fabulous wealth."],
          ["wonderful", "amazing"], ["ordinary"],
          ["fable", "infant"],
          ["极好的/惊人的：好到像只该在故事里听到", "传说中的：本义，出自故事的"],
          "fabula（故事）+ -ous → 像故事里那样的"),
        W("infant", "fari", "noun", "/ˈɪnfənt/",
          "in-（不）+ fant（fari 的现在分词 fans 说）→ 还不会说话的那个 → 婴儿",
          "古法语 enfant ← 拉丁语 infans（不会说话的）← in-（不）＋fari（说）的现在分词",
          "a very young child, especially one not yet walking",
          "the one who has everything to say and no words yet – 什么都想表达、却还没有话的那个",
          "他张着嘴使劲出声，但那些声音还拼不成词",
          ["婴儿", "幼儿"],
          ["The infant slept through the night.", "Infant care takes patience."],
          ["baby", "child"], ["adult"],
          ["fable", "fabulous"],
          ["婴儿/幼儿：还不会说话的那个"],
          "in-（不）+ fant（说）→ 还不会说话的那个"),
    ],
})

# ---------- flos（花）----------
families.append({
    "root": {
        "id": "flos", "root": "flos", "variants": ["flor", "flour", "flow"],
        "origin": "拉丁语 flos（属格 floris：花）；开到最盛即 flourish，"
                  "而 flour 本是「面粉中最好的那一层」（fleur de farine），故也归此支",
        "core_concept": "the best of a thing, come to full bloom / 一物最盛、最好的那一层",
        "core_image": "枝头那一朵开到最满，花瓣再展就要落了",
        "english_definition": "flower, bloom, the best part",
    },
    "concept": {
        "id": "concept-flos-bloom", "concept": "the best of a thing, come to full bloom",
        "chinese": "开到最盛", "core_image": "枝头那一朵开到最满，花瓣再展就要落了",
        "root_ids": ["flos"], "word_ids": [],
    },
    "domain": "domain-make",
    "words": [
        W("flower", "flos", "noun", "/ˈflaʊə(r)/",
          "flos（花）→ 植株开出来的那一朵",
          "古法语 flour ← 拉丁语 flos/floris（花）",
          "the coloured part of a plant that produces seeds",
          "the part a plant puts out when it has strength to spare – 植株攒足了劲才推出来的那一处",
          "枝上那处颜色一天天张开，花瓣一层压着一层",
          ["花", "开花"],
          ["She picked a yellow flower.", "The tree flowers in April."],
          ["blossom", "bloom"], [],
          ["flour", "flourish"],
          ["花：植株开出来的那一朵", "开花：推出那一朵这个动作"],
          "flos（花）→ 植株开出的那一朵"),
        W("flour", "flos", "noun", "/ˈflaʊə(r)/",
          "flos（花、最好的部分）→ fleur de farine（面之精）→ 面粉",
          "中古英语 flour（面之精），与 flower 同词分化 ← 拉丁语 flos（花、精华）",
          "powder made from ground wheat, used for baking",
          "the finest layer sifted out of the ground grain – 磨过的谷里筛出来的最细那一层",
          "粗的留在筛上，落下来的那层白得发亮",
          ["面粉"],
          ["Add two cups of flour.", "She dusted the board with flour."],
          ["meal", "powder"], [],
          ["flower", "flourish"],
          ["面粉：磨过的谷里筛出的最细那一层，本义即「面之精」"],
          "flos（精华）→ fleur de farine（面之精）→ 面粉"),
        W("flourish", "flos", "verb", "/ˈflʌrɪʃ/",
          "flor（花）+ -ish → 开到最盛 → 兴旺、茁壮",
          "古法语 florir ← 通俗拉丁语 florire ← 拉丁语 florere（开花）← flos（花）",
          "to grow well; to be successful and thriving",
          "the moment a thing puts out everything it has – 一物把攒下的劲全推出来那一刻",
          "那株移过来第二年就窜高一截，枝上密密都是花",
          ["茁壮成长", "兴旺", "繁荣"],
          ["The business flourished.", "Plants flourish in this soil."],
          ["thrive", "prosper"], ["fade", "decline"],
          ["flower", "flour"],
          ["茁壮成长/兴旺/繁荣：把攒下的劲全推出来、开到最盛"],
          "flor（花）+ -ish → 开到最盛"),
    ],
})

# ---------- heres（承继人）----------
families.append({
    "root": {
        "id": "heres", "root": "heres", "variants": ["her", "herit", "heir"],
        "origin": "拉丁语 heres（属格 heredis：继承人）；hereditare 是「接过来」，"
                  "英语 heir 经古法语 eir 入，h 是后来照拉丁语补写的",
        "core_concept": "the one whose hands the thing passes into next / 东西下一步落到谁手里",
        "core_image": "老人把那串钥匙放到一个人手心，自己的手就松开了",
        "english_definition": "heir, one who inherits",
    },
    "concept": {
        "id": "concept-heres-inherit", "concept": "the one whose hands the thing passes into next",
        "chinese": "接手之人", "core_image": "老人把那串钥匙放到一个人手心，自己的手松开了",
        "root_ids": ["heres"], "word_ids": [],
    },
    "domain": "domain-transfer",
    "words": [
        W("heir", "heres", "noun", "/eə(r)/",
          "heres（继承人）→ 依法接过家产的那个人",
          "古法语 eir ← 拉丁语 heres（继承人）；英语拼写的 h 是后来照拉丁语补的，不发音",
          "a person legally entitled to inherit property or a title",
          "the one named to receive when the holder lets go – 持有者松手时，被指名接住的那个",
          "文书上写着那个名字，老人一走东西就归他",
          ["继承人", "嗣子"],
          ["He is the sole heir.", "The heir to the throne was crowned."],
          ["successor", "son"], [],
          ["heritage", "inherit"],
          ["继承人/嗣子：持有者松手时被指名接住的那个"],
          "heres（继承人）→ 依法接过家产的那个人"),
        W("heritage", "heres", "noun", "/ˈherɪtɪdʒ/",
          "herit（继承）+ -age → 一代代传下来的那一份",
          "古法语 heritage ← heriter ← 晚期拉丁语 hereditare（继承）← heres",
          "traditions and buildings passed down from earlier generations",
          "what each generation hands on without being asked to – 每一代自然而然交下去的那一份",
          "老屋、老手艺、老规矩，都是上一辈没说什么就留下的",
          ["遗产", "传统", "文化遗产"],
          ["The town protects its heritage.", "Music is part of her heritage."],
          ["tradition", "legacy"], [],
          ["heir", "inherit"],
          ["遗产/文化遗产：一代代传下来的那一份", "传统：其中无形的那部分"],
          "herit（继承）+ -age → 一代代传下来的那份"),
        W("inherit", "heres", "verb", "/ɪnˈherɪt/",
          "in-（进入）+ herit（继承）→ 接进自己名下 → 继承",
          "古法语 enheriter ← 晚期拉丁语 inhereditare ← in＋heres（继承人）",
          "to receive property or a quality from someone before you",
          "the thing coming into your hands because it left another's – 因为别人松了手，它才落进你手里",
          "钥匙从那只手落进这只手，屋子从此归后者",
          ["继承", "遗传"],
          ["She inherited the house.", "He inherited his father's temper."],
          ["receive", "obtain"], [],
          ["heir", "heritage"],
          ["继承：因别人松手而落进自己手里", "遗传：性状同样由上一代传下来"],
          "in-（进入）+ herit（继承）→ 接进自己名下"),
    ],
})

# ---------- jocus（戏言）----------
families.append({
    "root": {
        "id": "jocus", "root": "jocus", "variants": ["joc", "jew", "joy"],
        "origin": "拉丁语 jocus（玩笑、戏言）；古法语 jouel（小玩物）派出 jewel 一支——"
                  "本指供人玩赏的小物，后专指宝石",
        "core_concept": "a small thing made for delight, not use / 拿来逗趣玩赏、不为实用的小东西",
        "core_image": "掌心里那个小玩意儿被翻来翻去，逗得旁人都笑了",
        "english_definition": "jest, plaything",
    },
    "concept": {
        "id": "concept-jocus-jest", "concept": "a small thing made for delight, not use",
        "chinese": "逗趣的小物", "core_image": "掌心那个小玩意儿被翻来翻去，逗得旁人都笑了",
        "root_ids": ["jocus"], "word_ids": [],
    },
    "domain": "domain-perceive",
    "words": [
        W("joke", "jocus", "noun", "/dʒəʊk/",
          "jocus（戏言）→ 说出来逗人笑的那句",
          "拉丁语 jocus（玩笑、戏言）",
          "something said or done to make people laugh",
          "the line said only for the laugh it gets – 只为博一声笑而说的那句",
          "他把最后半句一压低，满桌人先是静了一下才笑",
          ["玩笑", "笑话"],
          ["He told a bad joke.", "She takes a joke well."],
          ["humour", "wit"], [],
          ["jewel", "jewelry"],
          ["玩笑/笑话：只为博一声笑而说的那句"],
          "jocus（戏言）→ 说出来逗人笑的那句"),
        W("jewel", "jocus", "noun", "/ˈdʒuːəl/",
          "jocus（玩物）→ 古法语 jouel（小玩赏物）→ 宝石",
          "古法语 jouel（小玩物、饰件）← 拉丁语 jocus（玩笑、玩物）",
          "a precious stone; something highly valued",
          "the small bright thing kept only to be looked at – 留着只为看的那一小件亮东西",
          "绒布上那一点在灯下转个角度就换一种光",
          ["宝石", "珠宝", "珍品"],
          ["The crown holds many jewels.", "This book is a jewel."],
          ["stone", "treasure"], [],
          ["jewelry", "joke"],
          ["宝石/珠宝：留着只为看的那一小件亮东西", "珍品：以此喻极可贵之物"],
          "jocus（玩物）→ jouel（小玩赏物）→ 宝石"),
        W("jewelry", "jocus", "noun", "/ˈdʒuːəlri/",
          "jewel（宝石）+ -ry（成套）→ 成套的饰件",
          "古法语 juelerye ← jouel ← 拉丁语 jocus（玩物）",
          "rings, necklaces, and similar ornaments worn on the body",
          "the small bright things put on the body to be seen – 戴在身上、供人看的那些亮小件",
          "抽屉里一格一格摆着，戴出去时挑那么一两件",
          ["珠宝", "首饰"],
          ["She wore silver jewelry.", "The jewelry was locked away."],
          ["ring", "ornament"], [],
          ["jewel", "joke"],
          ["珠宝/首饰：戴在身上供人看的那些亮小件"],
          "jewel（宝石）+ -ry（成套）→ 成套的饰件"),
    ],
})

# ---------- dran（做、演）----------
families.append({
    "root": {
        "id": "dran", "root": "dran", "variants": ["dram", "drast"],
        "origin": "希腊语 dran（做、行动）；drama 本指「做出来给人看的一场」，"
                  "drastikos 指「见效猛的」——同一个「做」字，一支往台上走，一支往力道走",
        "core_concept": "something done in full view, with effect / 摆开来做给人看，且见得着效",
        "core_image": "台上那人一举手，底下几百双眼跟着动",
        "english_definition": "to do, act",
    },
    "concept": {
        "id": "concept-dran-act", "concept": "something done in full view, with effect",
        "chinese": "做给人看", "core_image": "台上那人一举手，底下几百双眼跟着动",
        "root_ids": ["dran"], "word_ids": [],
    },
    "domain": "domain-make",
    "words": [
        W("drama", "dran", "noun", "/ˈdrɑːmə/",
          "dran（做）→ drama（做出来的那一场）→ 戏剧",
          "晚期拉丁语 drama ← 希腊语 drama（一场演出）← dran（做、行动）",
          "a play for theatre or television; an exciting series of events",
          "the doing put on a raised floor so all can watch – 摆到台上、让所有人看着的那一番做",
          "幕布拉开，台上的事一件件当着众人做出来",
          ["戏剧", "剧本", "戏剧性事件"],
          ["She studies modern drama.", "The trial was full of drama."],
          ["play", "stage"], [],
          ["dramatic", "drastic"],
          ["戏剧/剧本：摆到台上做给人看的那一场", "戏剧性事件：现实里像那一场一样起伏的事"],
          "dran（做）→ drama（做出来的那一场）"),
        W("dramatic", "dran", "adjective", "/drəˈmætɪk/",
          "drama（一场演出）+ -ic → 像台上那一场的 → 引人注目的、剧烈的",
          "拉丁语 dramaticus ← 希腊语 dramatikos ← drama ← dran（做）",
          "sudden and noticeable; relating to plays",
          "of the kind that makes every head turn, as on a stage – 属于「一动就满座回头」那一类",
          "价钱一夜之间翻了一倍，第二天所有人都在说这事",
          ["剧烈的", "戏剧性的", "引人注目的"],
          ["Prices rose dramatically.", "She has dramatic talent."],
          ["striking", "sudden"], ["subtle"],
          ["drama", "drastic"],
          ["剧烈的/引人注目的：一动就满座回头那种", "戏剧性的：属于台上那一场的"],
          "drama（一场演出）+ -ic → 像台上那一场"),
        W("drastic", "dran", "adjective", "/ˈdræstɪk/",
          "drastikos（见效猛的）← dran（做）→ 下手重、来得急的",
          "希腊语 drastikos（有力的、见效的）← dran（做、行动）",
          "extreme and sudden, often severe in effect",
          "the kind of doing that leaves no room for halfway – 那种做法不留半途，一下到底",
          "他没有慢慢调，直接把整套换掉了",
          ["激烈的", "极端的", "彻底的"],
          ["They took drastic measures.", "A drastic change was needed."],
          ["severe", "radical"], ["mild", "gradual"],
          ["drama", "dramatic"],
          ["激烈的/极端的/彻底的：下手重、不留半途的那种做法"],
          "drastikos（见效猛）← dran（做）→ 下手重的"),
    ],
})

# ================= 补进已建模词根 =================
additions += [
    # fac —— 子代理报作新根 facere，但 fac 的 origin 就写「拉丁语 facere」
    W("fashion", "fac", "noun", "/ˈfæʃn/",
      "factio（做法、做成的样式）← facere（做）→ 一时通行的做法与样式",
      "古法语 fachon（式样）← 拉丁语 factio（做、样式）← facere（做）",
      "a popular style of clothing or behaviour; a way of doing something",
      "the way of making that everyone happens to follow this season – 这一季众人恰好都照着做的那个样式",
      "街上的裁法今年忽然都改成一个走向，去年那种没人做了",
      ["时尚", "流行式样", "方式"],
      ["Short coats are back in fashion.", "He did it in his own fashion."],
      ["style", "manner"], [],
      ["fact", "factory"],
      ["时尚/流行式样：一时通行的那种做法与样式", "方式：做一件事所取的那个做法"],
      "factio（做法、样式）← facere（做）→ 通行的样式"),
    W("feasible", "fac", "adjective", "/ˈfiːzəbl/",
      "fais（facere 做）+ -ible（可…的）→ 做得成的 → 可行的",
      "古法语 faisable（可做的）← faire ← 拉丁语 facere（做）",
      "possible to do or achieve",
      "the plan that survives the question can this actually be done – 经得住「这真做得成吗」一问的那个方案",
      "把工序一步步排下来，发现每一步都真办得到",
      ["可行的", "行得通的"],
      ["The plan seems feasible.", "It is not feasible in one week."],
      ["practical", "possible"], ["impossible"],
      ["fact", "fashion"],
      ["可行的/行得通的：经得住「真做得成吗」一问的那种"],
      "fais（做）+ -ible（可…的）→ 做得成的"),
    W("fax", "fac", "noun", "/fæks/",
      "facsimile（fac simile 做得一样）的截短 → 传过去的那份复本",
      "英语 fax 是 facsimile 的截短；facsimile ← 拉丁语 fac simile（做成相像的）← facere（做）",
      "a copy of a document sent over a phone line",
      "the copy made to come out the same at the far end – 在远处那头做出来、要求一模一样的复本",
      "这头把纸吃进去，那头一张一模一样的吐出来",
      ["传真", "传真件"],
      ["Send it by fax today.", "The fax never arrived."],
      ["copy", "print"], [],
      ["fact", "fashion"],
      ["传真/传真件：在远处做出来、要求一模一样的复本"],
      "facsimile（fac simile 做得一样）截短 → 传过去的复本"),
    # habere
    W("due", "habere", "adjective", "/djuː/",
      "debere（本该有却不在手上）← de＋habere（持有）→ 该给的、到期的",
      "古法语 deu（debvoir 的过去分词）← 拉丁语 debere（欠）← de＋habere（持有）",
      "owed as a debt or obligation; expected at a certain time",
      "what is on the books to be handed over, and the day it falls – 账上写着该交出去的那份，及该交的那天",
      "本子上记着日子，翻到那一页就知道该给了",
      ["应付的", "到期的", "预期的"],
      ["The rent is due on Friday.", "The train is due at six."],
      ["owing", "payable"], [],
      ["duty", "debt"],
      ["应付的/到期的：账上该交出去的那份及其期限", "预期的：按约该到的那个时候"],
      "debere（本该有却不在手）← de＋habere → 该给的"),
    W("duty", "habere", "noun", "/ˈdjuːti/",
      "due（该给的）+ -ty → 该做的那一份 → 职责；也指该缴的那笔税",
      "盎格鲁法语 duete ← deu（该给的）← 拉丁语 debere ← de＋habere（持有）",
      "something one is obliged to do; a tax on goods",
      "the share of work that is owed, not chosen – 分给你、非做不可的那一份，不是你挑的",
      "值班表上那格写着他的名字，轮到就得在那儿",
      ["职责", "义务", "关税"],
      ["It is your duty to report it.", "They paid duty on the import."],
      ["obligation", "tax"], [],
      ["due", "debt"],
      ["职责/义务：分给你、非做不可的那一份", "关税：进出货物该缴的那笔"],
      "due（该给的）+ -ty → 该做的那一份"),
    W("endeavor", "habere", "verb", "/ɪnˈdevə(r)/",
      "en-（使）+ devoir（该做之事）→ 把该做的当成自己的事去尽力 → 努力",
      "中古英语 endeveren，由 en-＋古法语 deveir（本分）← 拉丁语 debere ← de＋habere",
      "to try hard to do something",
      "taking what is owed as one's own and pushing at it – 把该做的那份认作自己的，往上使劲",
      "他把那份本不属他的活也接了过来，一样往前推",
      ["努力", "尽力", "尝试"],
      ["She endeavored to finish on time.", "It was a worthy endeavor."],
      ["strive", "attempt"], [],
      ["duty", "due"],
      ["努力/尽力/尝试：把该做的认作自己的、往上使劲"],
      "en-（使）+ devoir（该做之事）→ 当作己事去尽力"),
    # 其余单词补词
    W("insure", "cura", "verb", "/ɪnˈʃʊə(r)/",
      "en-/in-（使）+ sure（无忧）→ 先出一笔把后顾之忧买掉 → 投保",
      "英语 insure 是 ensure 的分化形 ← 古法语 enseurer ← 拉丁语 securus（无忧）← se-＋cura（挂心）",
      "to arrange for money to be paid if loss or damage happens",
      "paying a little now so the big loss is not yours to carry – 先付一点，把那笔大损失从自己肩上挪走",
      "每月扣掉一小笔，出事那天赔的是另一方",
      ["投保", "为…保险"],
      ["They insured the house against fire.", "Is the car insured?"],
      ["cover", "protect"], [],
      ["ensure", "cure"],
      ["投保/为…保险：先付一点，把大损失从自己肩上挪走"],
      "in-（使）+ sure（无忧）→ 出钱买掉后顾之忧"),
    W("grief", "gravis", "noun", "/ɡriːf/",
      "grev（gravis 重）→ 压在心上那份沉 → 悲痛",
      "古法语 grief（苦难）← grever（压重）← 拉丁语 gravare ← gravis（重的）",
      "very great sadness, especially after a death",
      "the weight that settles on the chest and does not lift – 压在胸口、久久不散的那份沉",
      "他坐着没说话，肩往下垮着，像有东西压在上头",
      ["悲痛", "悲伤"],
      ["She was overcome with grief.", "Time eases grief."],
      ["sorrow", "pain"], ["joy"],
      ["grave", "gravity"],
      ["悲痛/悲伤：压在胸口久久不散的那份沉"],
      "grev（重）→ 压在心上那份沉"),
    W("inertia", "ars", "noun", "/ɪˈnɜːʃə/",
      "in-（不）+ ert（ars 技艺、本事）→ 没本事动起来 → 惰性",
      "拉丁语 inertia（无能、懒惰）← iners（无技艺的）← in-（不）＋ars（技艺）",
      "a tendency to stay unchanged; resistance to being moved",
      "the state of a thing that will not start moving on its own – 一物自己不会动起来的那个状态",
      "推第一下最费劲，一旦动起来反倒不用那么使力",
      ["惯性", "惰性", "不作为"],
      ["The body has great inertia.", "Bureaucratic inertia slowed reform."],
      ["rest", "delay"], ["motion"],
      ["art", "artist"],
      ["惯性/惰性：一物自己不会动起来的那个状态", "不作为：把这份不动用在人或机构上"],
      "in-（不）+ ert（技艺、本事）→ 没本事动起来"),
    W("grant", "credere", "verb", "/ɡrɑːnt/",
      "credere（信托）→ creantare（许诺、应承）→ 应允给出 → 授予",
      "古法语 granter（应允）← creanter ← 通俗拉丁语 credentare ← 拉丁语 credere（信托）",
      "to agree to give or allow something formally",
      "handing over what was asked because you take the asker at their word – 信得过对方所求，就把那份给了",
      "他把申请翻了一遍，抬头说了句可以，笔一签就批了",
      ["授予", "准予", "补助金"],
      ["The city granted permission.", "She won a research grant."],
      ["allow", "award"], ["refuse"],
      ["credit", "credible"],
      ["授予/准予：信得过所求便把那份给出", "补助金：这样给出的那笔钱"],
      "credere（信托）→ creantare（应承）→ 应允给出"),
    W("futile", "fundere", "adjective", "/ˈfjuːtaɪl/",
      "fundere（倒出）→ futilis（一倒就漏的容器）→ 白费的",
      "拉丁语 futilis（易漏的、无用的）← fundere（倒出、流泻）",
      "having no useful result; pointless",
      "the leaky jar you keep filling that never holds anything – 一只漏的罐，一直往里倒却始终装不住",
      "水一勺勺倒进去，底下同时往外淌，怎么倒都不满",
      ["无用的", "徒劳的"],
      ["It was a futile attempt.", "Further talks proved futile."],
      ["useless", "empty"], ["effective"],
      ["diffuse", "confuse"],
      ["无用的/徒劳的：像一只漏的罐，倒进去也留不住"],
      "futilis（一倒就漏的容器）← fundere（倒出）"),
    W("glamor", "graphein", "noun", "/ˈɡlæmə(r)/",
      "grammar（学问、法术书）的苏格兰语变体 → 施在人身上的那层魅 → 魅力",
      "苏格兰语 glamer，为 grammar（旧时兼指法术之学）的变体 ← 希腊语 grammatikē ← graphein（刻写）",
      "an attractive and exciting quality",
      "the sheen laid over a thing so the eye will not look past it – 覆在一物上、叫人目光挪不开的那层光",
      "灯一打上去，本来平常的那身衣裳忽然亮得扎眼",
      ["魅力", "诱惑力", "光彩"],
      ["The city has a certain glamor.", "She was drawn by the glamor of fame."],
      ["charm", "beauty"], [],
      ["graphic", "biography"],
      ["魅力/诱惑力/光彩：覆在一物上、叫人目光挪不开的那层"],
      "grammar（旧兼指法术之学）的变体 ← graphein（刻写）"),
    W("incline", "klinein", "verb", "/ɪnˈklaɪn/",
      "in-（向内）+ cline（klinein 倾斜）→ 朝一边斜过去 → 倾向",
      "拉丁语 inclinare（使倾斜）← in＋clinare ← 希腊语 klinein（倾斜）",
      "to lean or slope; to tend toward an opinion",
      "the surface tipped so things roll one way, not the other – 面一斜，东西就只往那一边滚",
      "板子一头垫高，珠子全滚到低的那边去了",
      ["倾斜", "倾向", "斜坡"],
      ["The path inclines steeply here.", "I incline to agree with you."],
      ["slope", "tend"], [],
      ["climate", "climax"],
      ["倾斜/斜坡：面朝一边斜过去", "倾向：心里同样偏向某一边"],
      "in-（向内）+ cline（倾斜）→ 朝一边斜过去"),
    W("divorce", "vert", "noun", "/dɪˈvɔːs/",
      "di-（分开）+ vorce（vertere 转）→ 各自转开 → 离婚",
      "古法语 divorce ← 拉丁语 divortium（分离）← divertere（转开）← dis＋vertere（转）",
      "the legal ending of a marriage; a complete separation",
      "two who had faced each other turning away – 本来对着的两人各自转开身",
      "两人在桌两边签完字，起身朝相反方向走出门",
      ["离婚", "分离"],
      ["They filed for divorce.", "There is a divorce between theory and practice."],
      ["separation", "split"], ["marriage"],
      ["convert", "reverse"],
      ["离婚：本来对着的两人各自转开", "分离：两者之间同样转开、不再相接"],
      "di-（分开）+ vorce（转）→ 各自转开"),
]

# ================= 组装 =================
words = []
roots = []
concepts = []
domain_add = {}
for fam in families:
    r = dict(fam["root"]); r["word_ids"] = []
    roots.append(r)
    concepts.append(fam["concept"])
    domain_add.setdefault(fam["domain"], []).append(r["id"])
    words.extend(fam["words"])
words.extend(additions)

# ---- 生成期自检 ----
for w in words:
    for zh in w["chinese"]:
        assert not (len(zh) >= 2 and zh in w["core_image"]), \
            f"Q12 泄题：{w['id']} 的 core_image 点名义项「{zh}」"
    if len(w["chinese"]) >= 2:
        assert w["semantic_expansions"], f"Q1：{w['id']} 多义却无 semantic_expansions"
    assert w["recall_hint"], f"Q12：{w['id']} 缺 recall_hint"
    assert len(w["examples"]) >= 2, f"{w['id']} 例句不足 2 条"
assert len({w["id"] for w in words}) == len(words), "词条 id 有重复"
assert len({r["id"] for r in roots}) == len(roots), "词根 id 有重复"
wid = {w["id"] for w in words}
clash = [r["id"] for r in roots if r["id"] in wid]
assert not clash, f"词根 id 与本批单词同名，会产生自环边：{clash}"

OUT.write_text(json.dumps({
    "roots": roots, "concepts": concepts,
    "domain_add": domain_add, "words": words,
}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"wrote {OUT}: {len(words)} 词（{len(words)-len(additions)} 族词 + "
      f"{len(additions)} 补词）, {len(roots)} 新词根")
