#!/usr/bin/env python3
"""Generate batch38: absorb A+D class words into existing roots (zero-risk).

纯吸收批次：不新建词根/概念/域，只把 vetted 剩余词补进已建模词根的
word_ids。accesptable/acceptance 等 capere 词留到 cep 新根批次（见
HANDOFF 二·五），port/press/form/flu 裸词按决策标 loanword 不挂根（另批）。

词条结构照抄 batch37 的 W()。吸收动作由 merge 自动完成：
- words.json 追加词条
- relations.json 生成 root→word 边
- roots.json/concepts.json 的 word_ids 自动补齐
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "ai_pipeline" / "batch38.json"


def W(wid, rid, pos, ph, logic, origin, native, concept, image, zh, ex, syn, ant, rel, exp, hint):
    return {
        "id": wid, "word": wid, "pos": pos, "phonetic": ph,
        "decomposable": "root", "root_ids": [rid],
        "root_logic": logic, "origin": origin,
        "native_definition": native, "core_concept": concept,
        "core_image": image, "chinese": zh, "examples": ex,
        "synonyms": syn, "antonyms": ant, "related": rel,
        "semantic_expansions": exp, "recall_hint": hint,
    }


# 纯吸收：只挂既有词根。按 HANDOFF A/D 表（剔除需新建根/需拆分的词）。
# 无新词根、无新概念、无新域。
additions = [
    # ---- A 类：吸收到已建模词根 ----
    W("predominant", "domus", "adjective", "/prɪˈdɑːmɪnənt/",
      "pre-（在前）+ domin（主导）→ 排在最前面的主导 → 占主导地位的",
      "拉丁语 praedominari：prae-（在前）+ dominari（统治）",
      "more important or noticeable than anything else in a group",
      "standing out in front as the master does – 像主人那样排在最前、压住全场",
      "整片山坡上就数那棵巨杉最高最粗，远远先看见它",
      ["占主导的", "显著的"],
      ["The predominant color is blue.", "Agriculture is the predominant industry."],
      ["dominant", "prevailing"], ["minor"],
      ["dominate", "dominant"],
      ["占主导/显著：排在最前、最先被注意到的那一个"],
      "pre-（在前）+ domin（主导）→ 排在最前的主导"),
    W("expectation", "spect", "noun", "/ˌekspekˈteɪʃn/",
      "ex-（向外）+ spect（看）→ 朝外看的那个念头 → 期待",
      "拉丁语 exspectatio：ex-（向外）+ spectare（看）",
      "a strong belief that something will happen",
      "what one looks outward for – 朝外看去、等着它出现的东西",
      "站台边不停望向列车来的方向，心里早演好了那班车的样子",
      ["期待", "预期", "指望"],
      ["She has high expectations of her students.", "Sales met our expectations."],
      ["anticipation", "hope"], [],
      ["expect", "inspect", "prospect"],
      ["期待/预期：朝外看等着它出现","指望：对他人表现设定的标准"],
      "ex-（向外）+ spect（看）→ 朝外看、等它出现 → 期待"),
    W("importance", "port", "noun", "/ɪmˈpɔːrtns/",
      "im-（in- 向内）+ port（携带）→ 被携带进来的分量 → 重要",
      "拉丁语 importare（带入）的名词化——被带入的分量",
      "the quality of being significant or having great value",
      "weight carried into the matter – 被带进事情里的分量",
      "信封上那行字，落款人是谁，掂一下就知道轻重",
      ["重要性", "重大"],
      ["He stressed the importance of teamwork.", "The discovery is of great importance."],
      ["significance", "consequence"], [],
      ["important", "import", "transport"],
      ["重要性：被带进事情的重量"],
      "im-（向内）+ port（携带）→ 带进来的分量 → 重要"),
    W("porter", "port", "noun", "/ˈpɔːrtər/",
      "port（携带）+ -er（人）→ 帮着搬东西的人 → 搬运工",
      "拉丁语 portare（携带）+ -or（者）",
      "a person whose job is carrying luggage or goods",
      "the one who carries things – 专管搬运的那个人",
      "站台上推着行李车快步走的人，旅客的大箱小包都在他车上",
      ["搬运工", "门房"],
      ["The porter carried our bags to the room.", "A hotel porter opened the door."],
      ["carrier", "bearer"], [],
      ["portable", "transport", "important"],
      ["搬运工：专管搬运的人","门房：看门并帮提行李的人"],
      "port（携带）+ -er → 搬东西的人"),
    W("preceding", "ced", "adjective", "/prɪˈsiːdɪŋ/",
      "pre-（在前）+ ced（行走）→ 走在前面的 → 前述的",
      "拉丁语 praecedere：prae-（在前）+ cedere（行走）",
      "coming before something in time or order",
      "the one that goes in front – 走在前面、先到的那个",
      "翻回上一页，那行结论还在纸面上等着",
      ["在前的", "前述的"],
      ["The preceding chapter explains the theory.", "See the preceding paragraph."],
      ["previous", "prior"], ["following"],
      ["precede", "precedent", "concede"],
      ["在前的/前述的：走在前面的那一个"],
      "pre-（在前）+ ced（行走）→ 走在前面的"),
    W("preferable", "ferre", "adjective", "/ˈprefrəbl/",
      "prefer（更喜欢）+ -able（可）→ 更可取、更该选的",
      "prefer 的形容词：prae-（在前）+ ferre（带）",
      "better or more suitable, especially compared to others",
      "the one worth carrying out in front – 更值得拿到前面来的",
      "两杯水摆着，一杯带冰一杯温的，天热时手自然伸向那杯冰的",
      ["更可取的", "更好的"],
      ["Walking is preferable to driving.", "A quiet room is preferable."],
      ["better", "advisable"], [],
      ["prefer", "preference", "transfer"],
      ["更可取：更值得拿到前面来的"],
      "prefer（更喜欢）+ -able → 更该选的"),
    W("corresponding", "spondere", "adjective", "/ˌkɔːrəˈspɑːndɪŋ/",
      "cor-（相互）+ respond（回应）→ 彼此应得上的 → 相应的",
      "correspond 的形容词：com-（一起）+ respondere（回应）",
      "matching or connected with something else",
      "each answering to the other – 两边彼此应得上",
      "名单和座位号一一对好，拿号找座，一个都不落",
      ["相应的", "对应的"],
      ["Sales rose, and profits showed a corresponding increase.", "Fill in the corresponding boxes."],
      ["matching", "equivalent"], [],
      ["correspond", "correspondence", "response"],
      ["相应/对应：两边彼此应得上"],
      "cor-（相互）+ respond（回应）→ 彼此应得上 → 相应的"),
    W("resultant", "salire", "adjective", "/rɪˈzʌltənt/",
      "result（结果）+ -ant（…的）→ 作为结果而出现的",
      "result 的形容词：re-（回）+ salire（跳）",
      "happening as a result of something",
      "what leaps back out as the outcome – 事后蹦出来的那个结果",
      "比赛终场哨响，比分板上最终停下的那个数字",
      ["作为结果的", "由此产生的"],
      ["The resultant damage was extensive.", "Floods and the resultant chaos delayed us."],
      ["resulting", "consequent"], [],
      ["result", "insult", "consult"],
      ["作为结果：事后蹦出来的那个"],
      "result（结果）+ -ant → 作为结果出现的"),
    W("attractive", "tract", "adjective", "/əˈtræktɪv/",
      "at-（ad- 朝向）+ tract（拉）→ 能把人拉过去的 → 有吸引力的",
      "拉丁语 attrahere（拉近）：ad-（朝向）+ trahere（拉）",
      "pleasant to look at or pleasing to the mind",
      "pulling the eye toward it – 能把目光拉过去",
      "橱窗里那件展品，路过的人都会放慢脚步多看两眼",
      ["有吸引力的", "迷人的"],
      ["The offer is very attractive.", "She has an attractive smile."],
      ["appealing", "charming"], ["repellent"],
      ["attract", "attraction", "extract"],
      ["有吸引力：能把目光或兴趣拉过来"],
      "at-（朝向）+ tract（拉）→ 拉人过来的 → 有吸引力"),
    # ---- D 类：并入已建模词根 ----
    W("accord", "cors", "noun / verb", "/əˈkɔːrd/",
      "ac-（ad- 朝向）+ cord（心）→ 心朝向同一个地方 → 一致",
      "拉丁语 accordare（使同心）：ad-（朝向）+ cor/cordis（心）",
      "agreement or harmony between people; to be in agreement",
      "hearts turning toward the same point – 心朝向同一处",
      "两个人相视一点头，不用多说就知道想到一块去了",
      ["一致", "给予", "条约"],
      ["The two sides reached an accord.", "They acted in accord with the rules."],
      ["agreement", "harmony"], ["disagreement"],
      ["accordance", "accordingly", "cordial"],
      ["一致：心朝向同一处","给予：把这份一致当作认可送出","条约：国与国达成的协定"],
      "ac-（朝向）+ cord（心）→ 心朝同一处 → 一致"),
    W("accordance", "cors", "noun", "/əˈkɔːrdns/",
      "accord（一致）+ -ance → 一致的状态；常作 in accordance with（依照）",
      "accord 的名词化",
      "agreement or conformity; following a rule",
      "being in tune with the same heart – 与同一颗心合拍",
      "照着图纸一比一施工，每一个尺寸都对得上图纸",
      ["一致", "依照"],
      ["The work was done in accordance with the plan.", "in accordance with the law"],
      ["conformity", "compliance"], [],
      ["accord", "accordingly", "cordial"],
      ["依照：与规定保持一致"],
      "accord（一致）+ -ance → 一致的进行"),
    W("accordingly", "cors", "adverb", "/əˈkɔːrdɪŋli/",
      "according（一致）+ -ly → 与之相应地去办",
      "accord 的副词形式",
      "in a way that matches what was just said",
      "acting in line with the same tune – 顺着同一口径去办",
      "听到最新安排，马上把手里的计划照新口径改了",
      ["相应地", "因此"],
      ["The rules have changed, and we must act accordingly.", "He was told the news and behaved accordingly."],
      ["consequently", "therefore"], [],
      ["accord", "accordance", "cordial"],
      ["相应：照一致的标准去办"],
      "according（一致）+ -ly → 与之相应"),
    W("defeat", "fac", "noun / verb", "/dɪˈfiːt/",
      "de-（向下）+ feat（做）→ 把对方做出来的局面压下去 → 击败",
      "古法语 desfait：des-（去除）+ faire（做）；词根 facere（做）",
      "to win against someone; a failure to win",
      "undoing what the other side has done – 把对方做成的局面拆掉",
      "棋局最后一手落下，对方的布局被彻底拆解",
      ["击败", "失败"],
      ["The team defeated its rival.", "They suffered a heavy defeat."],
      ["beat", "conquer", "loss"], ["victory"],
      ["feat", "feature", "factory"],
      ["击败：把对方做成的事压下去","失败（名词）：被打败的结果"],
      "de-（向下）+ feat（做）→ 压掉对方所做的 → 击败"),
    W("feat", "fac", "noun", "/fiːt/",
      "feat（做）→ 做出来的不寻常之事 → 功绩",
      "古法语 fait：facere（做）的过去分词",
      "an achievement that needs great skill or strength",
      "a deed that is done with skill – 做得漂亮、做得出众的事",
      "杂技演员走完高空钢索，全场屏住的那口气终于呼出",
      ["功绩", "技艺"],
      ["The bridge is a feat of engineering.", "Climbing the peak was quite a feat."],
      ["achievement", "accomplishment"], [],
      ["defeat", "feature", "factory"],
      ["功绩：做出众的事情"],
      "feat（做）→ 做得出众的事"),
    W("feature", "fac", "noun / verb", "/ˈfiːtʃər/",
      "feat（做）+ -ure → 做出来摆给看的东西 → 特征、专题",
      "古法语 faiture（制作）：facere（做）",
      "a distinctive part or quality; to include as important",
      "what is made to stand out – 特意做出来让人注意的那部分",
      "一张脸上最抓人的那双眼睛，或杂志封面主推的那篇报道",
      ["特征", "特色", "以…为特色"],
      ["The phone has many new features.", "The film features a young actor."],
      ["characteristic", "attribute"], [],
      ["defeat", "feat", "factory"],
      ["特征：做出来让人注意的部分","以…为特色：把某物做成主打"],
      "feat（做）+ -ure → 做出来让人注意的"),
    W("probability", "prob", "noun", "/ˌprɑːbəˈbɪləti/",
      "prob（检验）+ -ability → 检验得出的可能性大小 → 概率",
      "拉丁语 probabilitas：probare（检验、证实）",
      "how likely something is to happen; chance",
      "the measured likelihood after testing – 检验之后得出的可能程度",
      "抛一百次硬币，正面朝上的次数大致各半，心里就有数了",
      ["概率", "可能性"],
      ["There is a high probability of rain.", "The probability of failure is low."],
      ["likelihood", "chance"], [],
      ["probable", "probe", "approve"],
      ["概率：检验得出的可能程度"],
      "prob（检验）+ -ability → 检验出的可能程度"),
    W("probable", "prob", "adjective", "/ˈprɑːbəbl/",
      "prob（检验）+ -able → 经检验很可能的 → 很可能的",
      "拉丁语 probabilis：probare（检验）",
      "likely to happen or be true",
      "passing the test of likelihood – 经得起'很可能'检验的",
      "看着天上堆起来的乌云，心里判断这场雨八九成要下",
      ["很可能的", "大概的"],
      ["It is probable that he will come.", "A probable cause of the delay is traffic."],
      ["likely", "possible"], ["improbable"],
      ["probability", "probe", "prove"],
      ["很可能：经得起可能性的检验"],
      "prob（检验）+ -able → 很可能的"),
    W("probe", "prob", "noun / verb", "/proʊb/",
      "prob（检验）→ 伸进去验一验里面是什么 → 探查；试探",
      "拉丁语 probare（检验）的名词形式",
      "a thorough investigation; to examine closely",
      "testing what lies inside – 伸进去验一验里面是什么",
      "医生轻轻试探伤口深浅，先弄清伤到哪一层，才敢判断",
      ["探查", "探针", "调查"],
      ["The committee probed into the scandal.", "A space probe explored the planet."],
      ["investigate", "examine"], [],
      ["probable", "probability", "prove"],
      ["探查：伸进去检验里面","探针：探查用的工具"],
      "prob（检验）→ 伸进去验 → 探查"),
    W("resist", "sta", "verb", "/rɪˈzɪst/",
      "re-（相反）+ sist（站立）→ 立住不动地顶回去 → 抵抗",
      "拉丁语 resistere：re-（相反）+ sistere（站立）；sistere 与 stare 同源",
      "to fight against something; to refuse to accept",
      "standing firm against the push – 顶着来势立住不退",
      "逆风里迈步，每一步都顶着风，人被往后推也不退",
      ["抵抗", "抵制", "忍住"],
      ["They resisted the invasion.", "She couldn't resist the chocolate."],
      ["withstand", "oppose"], ["yield", "submit"],
      ["resistance", "resistant", "constitute"],
      ["抵抗：顶着来势立住","忍住：抵御诱惑不随它走"],
      "re-（相反）+ sist（立）→ 顶着立住 → 抵抗"),
    W("resistance", "sta", "noun", "/rɪˈzɪstəns/",
      "resist（抵抗）+ -ance → 抵抗的状态或力量",
      "resistere 的名词化",
      "the act of fighting against something; a force opposing movement",
      "the standing firm against a push – 顶着来势立住的那股劲",
      "河道里竖起的石墩，水流冲过来，被它分开绕行",
      ["抵抗", "阻力"],
      ["The army met strong resistance.", "Copper has low electrical resistance."],
      ["opposition", "defiance"], [],
      ["resist", "resistant", "constitute"],
      ["抵抗：顶着来的状态","阻力：阻碍运动的力"],
      "resist（抵抗）+ -ance → 顶着的力"),
    W("resistant", "sta", "adjective", "/rɪˈzɪstənt/",
      "resist（抵抗）+ -ant → 能顶住而不被改变的",
      "resistere 的形容词",
      "not affected or harmed by something",
      "standing firm and unyielding – 立住不被动摇",
      "刷了防水层的木船，泡在水里也不烂不渗",
      ["抵抗的", "抗…的"],
      ["The material is resistant to heat.", "Some insects are resistant to pesticides."],
      ["immune", "unaffected"], ["susceptible"],
      ["resist", "resistance", "constitute"],
      ["抗…的：立住不被改变"],
      "resist（抵抗）+ -ant → 能顶住的"),
    W("constitute", "sta", "verb", "/ˈkɑːnstɪtuːt/",
      "con-（一起）+ stitut（立）+ -e → 一起立起来组成 → 构成",
      "拉丁语 constituere：com-（一起）+ statuere（立）；statuere 与 stare 同源",
      "to form or make up something",
      "standing together to form a whole – 一起立起来拼成整体",
      "几块木板拼在一起立起来，就成了一个架子",
      ["构成", "组成"],
      ["Women constitute half of the workforce.", "Such actions constitute a crime."],
      ["compose", "form"], [],
      ["institute", "substitute", "constitution"],
      ["构成：一起立起来组成整体"],
      "con-（一起）+ stitut（立）→ 立起来组成 → 构成"),
    W("institute", "sta", "noun / verb", "/ˈɪnstɪtuːt/",
      "in-（进入）+ stitut（立）→ 立起来使其开始运行 → 建立",
      "拉丁语 instituere：in-（进入）+ statuere（立）",
      "an organization for a purpose; to set up",
      "setting something standing so it runs – 立起来让它运转",
      "把一所学校立起来，先立规矩再招生，从此年年有人进来",
      ["机构", "建立"],
      ["She works at a research institute.", "They instituted new safety rules."],
      ["establish", "found"], [],
      ["constitute", "substitute", "institution"],
      ["机构：立起来运转的组织","建立：立起让它开始运转"],
      "in-（进入）+ stitut（立）→ 立起来运转 → 建立"),
    W("substitute", "sta", "noun / verb", "/ˈsʌbstɪtuːt/",
      "sub-（在下）+ stitut（立）→ 站在下面顶替 → 替代",
      "拉丁语 substituere：sub-（在下）+ statuere（立）",
      "a person or thing used instead of another; to replace",
      "one standing in below to take the place – 立在底下顶替的那个",
      "主力球员受伤下场，替补换上，位置照样有人顶住",
      ["替代品", "代替"],
      ["Honey can substitute for sugar.", "He came on as a substitute."],
      ["replace", "alternative"], [],
      ["constitute", "institute", "institution"],
      ["替代：站在下面顶替位置"],
      "sub-（在下）+ stitut（立）→ 站在下面顶替 → 替代"),
    W("continent", "tain", "noun", "/ˈkɑːntɪnənt/",
      "con-（一起）+ tin（握住）→ 连在一起握住的大陆 → 洲",
      "拉丁语 continere（连在一起）：com-（一起）+ tenere（握住）",
      "one of the large land masses of the Earth",
      "land held together in one continuous mass – 连成一片、握在一起的大陆",
      "从飞机上往下看，陆地的边界连成一大片，中间没有断",
      ["大陆", "洲"],
      ["Africa is a continent.", "The five continents were once connected."],
      ["landmass"], [],
      ["continual", "continuous", "contain"],
      ["大陆：连成一片、握在一起的地",
        "洲：地球上连成整块的大陆"],
      "con-（一起）+ tin（握住）→ 连住的大陆"),
    W("continual", "tain", "adjective", "/kənˈtɪnjuəl/",
      "con-（一起）+ tin（握住）+ -ual → 一直握在一起不松 → 连续不断的",
      "拉丁语 continuus：com-（一起）+ tenere（握住）",
      "happening repeatedly without stopping",
      "held together without a break – 一直连着没断",
      "楼上装修的电钻声一阵接一阵，从早到晚没停过",
      ["连续的", "频繁的"],
      ["There was continual noise from the street.", "Continual interruptions made work hard."],
      ["constant", "ceaseless"], ["intermittent"],
      ["continuous", "continent", "contain"],
      ["连续：一直连着没断","频繁：隔不多久又来一次"],
      "con-（一起）+ tin（握）+ -ual → 一直连着"),
    W("continuous", "tain", "adjective", "/kənˈtɪnjuəs/",
      "con-（一起）+ tin（握住）+ -uous → 不间断的",
      "continuus 的另一形容词形式",
      "happening without any pause or break",
      "held in one unbroken line – 一条线连到底",
      "那根水管里的水从早流到晚，中间没有一刻停",
      ["连续的", "持续的"],
      ["The road has a continuous white line.", "Continuous rain caused flooding."],
      ["unbroken", "constant"], ["broken", "intermittent"],
      ["continual", "continent", "contain"],
      ["连续：一条线不断"],
      "con-（一起）+ tin（握）+ -uous → 不间断的"),
    W("stationery", "sta", "noun", "/ˈsteɪʃəneri/",
      "station（站）+ -ery → 摆在书桌'站'的地方的用品 → 文具",
      "拉丁语 statio（站立之处）；与 stare（站）同源",
      "materials for writing, such as paper and pens",
      "things that sit by the writing stand – 摆在书写之处的东西",
      "书桌角上一叠信纸、几支笔、一瓶墨水，写东西的家伙事都在",
      ["文具"],
      ["The shop sells stationery and books.", "She bought some stationery for school."],
      ["paper", "pens"], [],
      ["station", "static", "statistical"],
      ["文具：摆在书写之处的用品"],
      "station（站）+ -ery → 摆在书桌边的文具"),
    W("statistical", "sta", "adjective", "/stəˈtɪstɪkl/",
      "statist（统计）+ -ical → 与统计有关的",
      "statistic ← 德语 Statistik ← 拉丁语 status（状况，站着的情形）；与 stare 同源",
      "relating to statistics or numbers that describe data",
      "about the standing facts counted up – 把站着的实况数出来",
      "那叠问卷上的勾选被一个个数出来，折成百分比画成图",
      ["统计的", "统计学的"],
      ["Statistical analysis supports the finding.", "The data show a statistical increase."],
      ["numerical", "quantitative"], [],
      ["station", "state", "stationery"],
      ["统计的：把实况数出来"],
      "stat（站）+ -istical → 把实况数出来"),
    W("stay", "sta", "verb / noun", "/steɪ/",
      "sta（站立）→ 立住不动 → 停留",
      "古法语 ester / rester：拉丁语 stare（站立）",
      "to remain in one place; a period of remaining",
      "standing in place, not moving off – 立在那儿不挪动",
      "逛到街角那家店就站住了，这一站就是一下午",
      ["停留", "暂住", "保持"],
      ["Please stay here until I return.", "They stayed at a hotel for two nights."],
      ["remain", "linger"], ["leave", "depart"],
      ["station", "static", "constant"],
      ["停留：立住不动","暂住：在一处住下不动","保持：维持在某种状态不离开"],
      "sta（站立）→ 立住不动 → 停留"),
]

OUT.write_text(json.dumps({
    "words": additions,
}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"wrote {OUT}: {len(additions)} words (纯吸收，无新根)")

# 提示：D 类 feat/defeat 归 fac 已在其中；cep/tangere/vid 词另批处理。
