#!/usr/bin/env python3
"""Generate batch61: 6 新词根 + 19 补词。

新根（各族在考研词表内均有 3 个以上成员）：
  putare（算、估）    compute / count / discount / dispute / deputy
  fallere（使失足）   fail / failure / false / fault / faulty
  densus（稠密）      dense / density / condense
  discus（圆盘）      disc / dish / desk
  phainein（显现）    emphasis / fantasy / fancy
  fatum（所言定数）   fate / fatal / fairy

补进已建模根（含两处「同根不同拉丁词形」的纠正）：
  plic  ← employ / employee / employer / exploit
        子代理报作新根 plicare，但 plic 的 origin 就写 plicare，是同一个根
  ag    ← embassy / essay / exam
        同理，子代理报作 agere，而 ag 的 origin 已写 agere
  habere ← enable / disable / endeavor    dare ← endow / dose
  legere ← elite       integer ← entire   cura ← ensure
  liber ← deliver / delivery              plic ← display
  gradus ← degree      sidus ← desire     spirare ← expire
  cernere ← discreet   charta ← discard   serere ← exert
  fidere ← defy

写法：W() 定参函数。Q12/Q1 自检与自环断言均在生成期。
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "ai_pipeline" / "batch61.json"


def W(wid, rid, pos, ph, logic, origin, native, concept, image, zh, ex, syn, ant, rel, exp, hint):
    return {
        "id": wid, "word": wid, "pos": pos, "phonetic": ph,
        "decomposable": "root", "root_ids": [rid],
        "root_logic": logic, "origin": origin,
        "native_definition": native, "core_concept": concept,
        "core_image": image, "chinese": zh, "examples": ex,
        "synonyms": syn, "antonyms": ant, "related": rel,
        "semantic_expansions": exp, "recall_hint": hint,
    }


families = []
additions = []

# ---------- putare（算、估）----------
families.append({
    "root": {
        "id": "putare", "root": "putare", "variants": ["put", "pute", "count"],
        "origin": "拉丁语 putare（修剪，引申为清点、估算）；computare（com＋putare 合起来算）"
                  "经古法语 conter 派出 count 一支",
        "core_concept": "reckoning a thing up to settle what it comes to / 把东西点算一遍，定出它算多少",
        "core_image": "手指点着桌上的钱一枚枚过，嘴里跟着报数",
        "english_definition": "to prune, reckon, estimate",
    },
    "concept": {
        "id": "concept-putare-reckon", "concept": "reckoning a thing up to settle what it comes to",
        "chinese": "点算估定", "core_image": "手指点着桌上的钱一枚枚过，嘴里跟着报数",
        "root_ids": ["putare"], "word_ids": [],
    },
    "domain": "domain-perceive",
    "words": [
        W("count", "putare", "verb", "/kaʊnt/",
          "com-（合起来）+ put（算）→ computare（合算）经古法语 conter → 一个个点过",
          "古法语 conter ← 拉丁语 computare（合算）← com＋putare（清点）",
          "to say numbers in order; to find the total of things",
          "going over items one by one so none is passed twice – 一件件点过去，不重不漏",
          "他指着一排箱子挨个点，点到哪儿手就停在哪儿",
          ["数", "计数", "算作"],
          ["She counted the coins twice.", "Every vote counts here."],
          ["number", "add"], [],
          ["compute", "discount"],
          ["数/计数：一件件点过去定出总数", "算作：把某物点进这一类里"],
          "com-（合起来）+ put（算）→ 一个个点过"),
        W("compute", "putare", "verb", "/kəmˈpjuːt/",
          "com-（合起来）+ pute（算）→ 把各项合起来算出结果",
          "拉丁语 computare（合算）← com＋putare（清点、估算）",
          "to calculate an answer using numbers",
          "putting all the parts together to get one figure – 把各项合到一处，算出一个数",
          "各栏数字挨着加下来，最后一格填出总数",
          ["计算", "算出"],
          ["The program computes the average.", "He computed the cost in minutes."],
          ["calculate", "reckon"], [],
          ["count", "discount"],
          ["计算/算出：把各项合起来得出一个数"],
          "com-（合起来）+ pute（算）→ 合起来算出结果"),
        W("discount", "putare", "noun", "/ˈdɪskaʊnt/",
          "dis-（去掉）+ count（算）→ 从原数里算掉一部分 → 折扣",
          "古法语 desconter（扣除）← dis＋conter ← 拉丁语 computare",
          "an amount taken off the usual price; to treat as unimportant",
          "the part struck off the total before you pay – 付钱之前从总数里划掉的那一截",
          "标价被笔划掉，旁边写了个小些的数",
          ["折扣", "打折", "不予考虑"],
          ["They offered a ten percent discount.", "Do not discount her advice."],
          ["reduction", "cut"], [],
          ["count", "compute"],
          ["折扣/打折：从总数里算掉的那一截", "不予考虑：把某说法从考量里划掉"],
          "dis-（去掉）+ count（算）→ 从原数里算掉一部分"),
        W("dispute", "putare", "noun", "/dɪˈspjuːt/",
          "dis-（分开）+ pute（算）→ 各算各的、算不到一处 → 争执",
          "古法语 desputer ← 拉丁语 disputare（各自估算、辩论）← dis＋putare",
          "a disagreement or argument between sides",
          "two reckonings that will not come out the same – 两边各算一遍，算出来的数对不上",
          "两人各拿一张纸算同一笔账，末了数字差着一截",
          ["争执", "争论", "质疑"],
          ["The dispute lasted for months.", "Nobody disputes her skill."],
          ["quarrel", "argue"], ["agreement"],
          ["compute", "count"],
          ["争执/争论：各算各的、算不到一处", "质疑：不认对方那笔算法"],
          "dis-（分开）+ pute（算）→ 各算各的、对不上"),
        W("deputy", "putare", "noun", "/ˈdepjuti/",
          "de-（往下）+ put（派定）→ 被指派下来顶事的人 → 副职",
          "古法语 deputé ← 晚期拉丁语 deputare（指派）← de＋putare（估定、派定）",
          "a person given authority to act for someone else",
          "the one named to stand in when the first is away – 被点定、正主不在时顶上的那个",
          "名册上头一个名字底下写着第二个，正主不在就他签字",
          ["副手", "代理人", "议员"],
          ["The deputy signed in her absence.", "He was elected deputy last year."],
          ["assistant", "delegate"], [],
          ["compute", "count"],
          ["副手/代理人：被点定、正主不在时顶上的那个", "议员：受选派代表一方的那个"],
          "de-（往下）+ put（派定）→ 被指派顶事的人"),
    ],
})

# ---------- fallere（使失足）----------
families.append({
    "root": {
        "id": "fallere", "root": "fallere", "variants": ["fail", "fals", "fault"],
        "origin": "拉丁语 fallere（使跌倒、骗过），过去分词 falsus；"
                  "本义是脚下一空、人没接住，故「失手」与「假的」出自同一意象",
        "core_concept": "the footing giving way so the thing does not hold / 脚下一空，事没托住",
        "core_image": "踩上去那块板忽然塌下去，手里的东西一起掉了",
        "english_definition": "to trip up, deceive",
    },
    "concept": {
        "id": "concept-fallere-give-way", "concept": "the footing giving way so the thing does not hold",
        "chinese": "脚下一空", "core_image": "踩上去那块板忽然塌下去，手里的东西一起掉了",
        "root_ids": ["fallere"], "word_ids": [],
    },
    "domain": "domain-force",
    "words": [
        W("fail", "fallere", "verb", "/feɪl/",
          "fallere（使跌倒）→ 该托住的没托住 → 没做成",
          "古法语 faillir ← 通俗拉丁语 fallire ← 拉丁语 fallere（使跌倒、骗过）",
          "to not succeed in doing something; to stop working",
          "the moment the thing that should have held gives out – 本该托住的那一下没托住",
          "绳子在半空断了，吊着的东西直接落到地上",
          ["失败", "不及格", "失灵"],
          ["The plan failed completely.", "The engine failed on the hill."],
          ["collapse", "sink"], ["succeed"],
          ["failure", "false"],
          ["失败/不及格：该成的没成", "失灵：该运转的忽然不动了"],
          "fallere（使跌倒）→ 该托住的没托住"),
        W("failure", "fallere", "noun", "/ˈfeɪljə(r)/",
          "fail（没做成）+ -ure → 没做成这件事，或没做成的那个人/物",
          "英语 failure，来自 fail ← 拉丁语 fallere",
          "a lack of success; a person or thing that does not work",
          "what is left after the footing gave way – 塌下去之后剩下的那个局面",
          "地上一堆碎的，旁边立着那截断了的绳",
          ["失败", "故障", "失败者"],
          ["The project ended in failure.", "A power failure hit the town."],
          ["defeat", "breakdown"], ["success"],
          ["fail", "false"],
          ["失败：没做成这件事", "故障：机件该动而不动那一下", "失败者：屡屡没成的那个人"],
          "fail（没做成）+ -ure → 没做成的局面"),
        W("false", "fallere", "adjective", "/fɔːls/",
          "falsus（fallere 的过去分词）→ 骗过人的 → 假的、不实的",
          "拉丁语 falsus（假的、骗人的），fallere（骗过）的过去分词",
          "not true or real; intended to deceive",
          "the thing that looks sound until your weight is on it – 看着结实，一压上去才知道不是",
          "那块板漆得跟别处一样，踩上去才发现底下是空的",
          ["错误的", "假的", "虚伪的"],
          ["He gave a false name.", "That assumption is false."],
          ["fake", "wrong"], ["true", "genuine"],
          ["fault", "fail"],
          ["错误的：与实际不符", "假的：造出来冒充真的", "虚伪的：待人时装出的那副样子"],
          "falsus（fallere 的过去分词）→ 骗过人的、假的"),
        W("fault", "fallere", "noun", "/fɔːlt/",
          "fallere（失手）→ 出岔的那一处 → 过失、缺陷",
          "古法语 faute ← 通俗拉丁语 fallita（失手之处）← 拉丁语 fallere",
          "a mistake or weakness; responsibility for something wrong",
          "the one spot where it gave way, and whose hand let it – 塌掉的那一处，以及那是谁的手松了",
          "查下来是那一颗螺丝没拧紧，别处都好",
          ["过失", "缺点", "故障"],
          ["It was my fault entirely.", "The machine has a design fault."],
          ["mistake", "flaw"], ["merit"],
          ["faulty", "false"],
          ["过失：出岔那一下该谁负责", "缺点/故障：物件上出岔的那一处"],
          "fallere（失手）→ 出岔的那一处"),
        W("faulty", "fallere", "adjective", "/ˈfɔːlti/",
          "fault（出岔之处）+ -y → 带着毛病的",
          "英语 faulty，来自 fault ← 拉丁语 fallere",
          "not working properly because of a defect",
          "of the kind that will give way somewhere – 属于「总有一处会塌」的那种",
          "同一批插头里有几个一插就跳闸，别的都正常",
          ["有缺陷的", "有故障的"],
          ["The faulty wiring caused the fire.", "They replaced the faulty part."],
          ["broken", "imperfect"], ["sound"],
          ["fault", "fail"],
          ["有缺陷的/有故障的：带着毛病、总有一处会塌的那种"],
          "fault（出岔之处）+ -y → 带着毛病的"),
    ],
})

# ---------- densus（稠密）----------
families.append({
    "root": {
        "id": "densus", "root": "densus", "variants": ["dens", "dense"],
        "origin": "拉丁语 densus（稠的、挤实的），动词 densare 表「使变稠」",
        "core_concept": "packed so tight there is no gap left / 挤得实实的，没留缝",
        "core_image": "一把棉花被手攥紧，攥到指缝里再挤不出空气",
        "english_definition": "thick, crowded",
    },
    "concept": {
        "id": "concept-densus-packed", "concept": "packed so tight there is no gap left",
        "chinese": "挤得实", "core_image": "一把棉花被攥紧，攥到指缝里再挤不出空气",
        "root_ids": ["densus"], "word_ids": [],
    },
    "domain": "domain-shape",
    "words": [
        W("dense", "densus", "adjective", "/dens/",
          "densus（稠的）→ 单位地方里挤了很多 → 密集的",
          "拉丁语 densus（稠密的、挤实的）",
          "having parts packed closely together; hard to see through",
          "so much crowded into one space that little else fits – 一处地方里挤了太多，别的塞不进",
          "树干挨着树干，走进去几步就看不见来路",
          ["密集的", "浓密的", "愚钝的"],
          ["The forest is very dense here.", "Dense fog closed the airport."],
          ["thick", "close"], ["thin", "loose"],
          ["density", "condense"],
          ["密集的/浓密的：一处地方里挤了很多", "愚钝的：脑子像塞满了，转不动"],
          "densus（稠的）→ 一处地方里挤了很多"),
        W("density", "densus", "noun", "/ˈdensəti/",
          "dense（密集的）+ -ity → 挤得多密这个量",
          "拉丁语 densitas（稠密）← densus",
          "how tightly packed something is; mass per unit of volume",
          "the measure of how much is crowded into one space – 一处地方里究竟挤了多少的那个量",
          "同样大的两只盒子，一只沉手一只轻，装的东西疏密不同",
          ["密度", "稠密度"],
          ["Bone density falls with age.", "The city has high population density."],
          ["concentration", "weight"], [],
          ["dense", "condense"],
          ["密度/稠密度：一处地方里挤了多少的那个量"],
          "dense（密集的）+ -ity → 挤得多密这个量"),
        W("condense", "densus", "verb", "/kənˈdens/",
          "con-（一起）+ dense（挤实）→ 往一处挤紧 → 压缩、凝结",
          "拉丁语 condensare（使变稠）← con＋densare ← densus（稠的）",
          "to make something smaller or shorter; to change from gas to liquid",
          "squeezing what was spread out into one tighter mass – 把摊开的往一处挤成更紧的一团",
          "满满一锅汤熬到只剩碗底那点，味道全收在里头",
          ["压缩", "浓缩", "凝结"],
          ["He condensed the report to one page.", "Steam condenses on cold glass."],
          ["compress", "shorten"], ["expand"],
          ["dense", "density"],
          ["压缩/浓缩：把摊开的往一处挤紧", "凝结：气挤成液那一下"],
          "con-（一起）+ dense（挤实）→ 往一处挤紧"),
    ],
})

# ---------- discus（圆盘）----------
families.append({
    "root": {
        "id": "discus", "root": "discus", "variants": ["disc", "dish", "desk", "disk"],
        "origin": "拉丁语 discus（圆盘、掷饼）← 希腊语 diskos；"
                  "扁圆一片这个形状，派出盘子、圆片、桌板三支",
        "core_concept": "a flat round thing you set things on or throw / 扁圆的一片，用来盛放或掷出",
        "core_image": "一块扁圆的板，边上一圈微微翘起",
        "english_definition": "disc, flat round plate",
    },
    "concept": {
        "id": "concept-discus-flat-round", "concept": "a flat round thing you set things on or throw",
        "chinese": "扁圆一片", "core_image": "一块扁圆的板，边上一圈微微翘起",
        "root_ids": ["discus"], "word_ids": [],
    },
    "domain": "domain-shape",
    "words": [
        W("disc", "discus", "noun", "/dɪsk/",
          "discus（圆盘）→ 扁而圆的那一片",
          "拉丁语 discus（圆盘）← 希腊语 diskos（掷饼）",
          "a thin flat round object",
          "the thin round piece you can spin between two fingers – 两指一夹就能转起来的那薄薄一圆片",
          "薄薄一片圆的，对着光能看见一圈圈细纹",
          ["圆盘", "唱片", "椎间盘"],
          ["He put the disc in the player.", "She slipped a disc in her back."],
          ["circle", "plate"], [],
          ["dish", "desk"],
          ["圆盘：扁而圆的那一片", "唱片：刻了纹的那种圆片", "椎间盘：脊椎间垫着的那片圆软骨"],
          "discus（圆盘）→ 扁而圆的那一片"),
        W("dish", "discus", "noun", "/dɪʃ/",
          "discus（圆盘）经古英语 disc → 盛食物的那只浅圆器",
          "古英语 disc（盘）← 拉丁语 discus（圆盘）← 希腊语 diskos",
          "a shallow container for food; food prepared in a particular way",
          "the shallow round thing food is set into – 把菜放进去的那只浅圆器",
          "浅浅一只圆的，菜盛在里头边上还留一圈",
          ["盘子", "菜", "一道菜"],
          ["Wash the dishes after dinner.", "This dish takes an hour to cook."],
          ["plate", "bowl"], [],
          ["disc", "desk"],
          ["盘子：盛食物的那只浅圆器", "菜/一道菜：装在那只器里端上来的那样吃食"],
          "discus（圆盘）→ 盛食物的浅圆器"),
        W("desk", "discus", "noun", "/desk/",
          "discus（圆盘、板）经中世纪拉丁语 desca → 写字用的那块板 → 书桌",
          "中世纪拉丁语 desca（桌）← 拉丁语 discus（圆盘、扁板）",
          "a piece of furniture with a flat top for writing or working",
          "the flat board set at hand height to work on – 架到手边高度、供人在上头做事的那块平板",
          "一块平板架在两侧支架上，胳膊搭上去正好",
          ["书桌", "办公桌", "服务台"],
          ["Papers covered the whole desk.", "Ask at the front desk."],
          ["table", "counter"], [],
          ["disc", "dish"],
          ["书桌/办公桌：架到手边、供人做事的那块平板", "服务台：同样一块板，隔在办事人与客人之间"],
          "discus（扁板）→ desca → 写字用的那块板"),
    ],
})

# ---------- phainein（显现）----------
families.append({
    "root": {
        "id": "phainein", "root": "phainein", "variants": ["phas", "phan", "fan"],
        "origin": "希腊语 phainein（使显现、露出来）；phasis 表「显出的相」，"
                  "phantasia 表「心里现出的影」，英语 fantasy、fancy 同出后者",
        "core_concept": "bringing a thing into sight so it shows / 让某样东西现出来、被看见",
        "core_image": "帘子一拉开，原先看不见的那样东西露在光里",
        "english_definition": "to show, bring to light",
    },
    "concept": {
        "id": "concept-phainein-show", "concept": "bringing a thing into sight so it shows",
        "chinese": "使之现出", "core_image": "帘子一拉开，原先看不见的那样东西露在光里",
        "root_ids": ["phainein"], "word_ids": [],
    },
    "domain": "domain-perceive",
    "words": [
        W("emphasis", "phainein", "noun", "/ˈemfəsɪs/",
          "em-（en- 在内）+ phas（显现）+ -is → 把某一处特意显出来 → 强调",
          "希腊语 emphasis（显露、着重）← en＋phainein（使显现）",
          "special importance given to something in speaking or writing",
          "the one part pushed forward so the eye goes there first – 特意推到前头、让人先看见的那一处",
          "整段话里只有那一句被放慢了，听的人都记住了它",
          ["强调", "重点", "重音"],
          ["She put emphasis on safety.", "The emphasis falls on the first syllable."],
          ["stress", "weight"], [],
          ["fantasy", "fancy"],
          ["强调/重点：特意显出来、让人先看见的那一处", "重音：读音上被显出来的那一节"],
          "em-（在内）+ phas（显现）→ 特意把一处显出来"),
        W("fantasy", "phainein", "noun", "/ˈfæntəsi/",
          "phantasia（心里现出的影）← phainein（使显现）→ 只在心里显出、不在眼前的那些",
          "古法语 fantasie ← 拉丁语 phantasia ← 希腊语 phantasia（想象）← phainein",
          "something imagined that is not real; a story of magical events",
          "the picture that shows only inside the head – 只在脑子里现出来、外头没有的那幅",
          "闭上眼那幅景象清清楚楚，睁眼什么也没有",
          ["幻想", "想象", "奇幻作品"],
          ["He lives in a fantasy world.", "The book is pure fantasy."],
          ["dream", "illusion"], ["reality"],
          ["fancy", "emphasis"],
          ["幻想/想象：只在脑子里现出来的那幅", "奇幻作品：把这类景象写成的故事"],
          "phantasia（心里现出的影）→ 只在心里显出的那些"),
        W("fancy", "phainein", "verb", "/ˈfænsi/",
          "fantasy 的截短形 → 心里现出个念头 → 觉得想要、喜欢；形容词指花哨",
          "中古英语 fantsy，fantasy 的截短 ← 希腊语 phantasia ← phainein",
          "to want or like something; elaborately decorated",
          "the notion that surfaces on its own, unbidden – 没人叫它、自己在心里冒出来的那个念头",
          "橱窗前站了一会儿，脚就是不肯往前挪",
          ["想要", "喜欢", "花哨的"],
          ["Do you fancy a cup of tea?", "She wore a fancy hat."],
          ["desire", "showy"], ["plain"],
          ["fantasy", "emphasis"],
          ["想要/喜欢：心里自己冒出来的那个念头", "花哨的：外表现得过多、招眼的那种"],
          "fantasy 截短 → 心里自己冒出的念头"),
    ],
})

# ---------- fatum（所言定数）----------
families.append({
    "root": {
        "id": "fatum", "root": "fatum", "variants": ["fat", "fai", "fay"],
        "origin": "拉丁语 fatum（神所说定的事）← fari（说）的过去分词中性形；"
                  "Fata（司命三女神）经古法语 fae 派出 fairy 一支",
        "core_concept": "what was spoken once and cannot be taken back / 一旦说定就收不回的那件事",
        "core_image": "一句话说出口，纸上就照那句写下，谁也改不动",
        "english_definition": "that which has been spoken, destiny",
    },
    "concept": {
        "id": "concept-fatum-spoken-doom", "concept": "what was spoken once and cannot be taken back",
        "chinese": "说定之数", "core_image": "一句话说出口，纸上就照那句写下，谁也改不动",
        "root_ids": ["fatum"], "word_ids": [],
    },
    "domain": "domain-force",
    "words": [
        W("fate", "fatum", "noun", "/feɪt/",
          "fatum（所说定之事）→ 由不得人改的那个去向",
          "拉丁语 fatum（命定之事）← fari（说）的过去分词",
          "the power thought to decide events; what finally happens to someone",
          "the outcome already spoken, whatever one does – 早已说定的那个结果，人怎么动都一样",
          "签抽出来了，上面写着什么就照着走，重抽也没用",
          ["命运", "结局", "下场"],
          ["She accepted her fate calmly.", "The fate of the ship is unknown."],
          ["destiny", "outcome"], ["choice"],
          ["fatal", "fairy"],
          ["命运：由不得人改的那个去向", "结局/下场：那个去向最后落成的样子"],
          "fatum（所说定之事）→ 由不得人改的去向"),
        W("fatal", "fatum", "adjective", "/ˈfeɪtl/",
          "fatum（定数）+ -al → 关乎定数的 → 致命的、决定性的",
          "拉丁语 fatalis（命定的、致死的）← fatum",
          "causing death; leading to disaster",
          "the one stroke after which nothing can be redone – 这一下过后，什么都补不回来了",
          "那一刀下去就没有第二次机会，别的伤都还能治",
          ["致命的", "毁灭性的", "命中注定的"],
          ["He suffered a fatal injury.", "That was a fatal mistake."],
          ["deadly", "mortal"], ["harmless"],
          ["fate", "fairy"],
          ["致命的：这一下过后补不回来", "毁灭性的：同样不可挽回，用在局面上", "命中注定的：早已说定、避不开的"],
          "fatum（定数）+ -al → 关乎定数、补不回来"),
        W("fairy", "fatum", "noun", "/ˈfeəri/",
          "Fata（司命女神）→ 古法语 fae（有法力的女子）+ -ry → 小精灵",
          "古法语 faerie（法术、精灵之境）← fae ← 拉丁语 Fata（司命三女神）← fatum",
          "a small imaginary being with magic powers",
          "the small being said to hold sway over how things turn out – 传说能左右事情走向的那个小小者",
          "书里画着一个巴掌大的身影，背后两片薄翅",
          ["仙女", "小精灵"],
          ["She read a fairy tale aloud.", "Children believe in fairies."],
          ["spirit", "ghost"], [],
          ["fate", "fatal"],
          ["仙女/小精灵：传说能左右事情走向的那个小小者"],
          "Fata（司命女神）→ fae（有法力者）→ 小精灵"),
    ],
})

# ================= 补进已建模词根 =================
# 其中 plic 与 ag 两族是纠正：子代理分别报作新根 plicare / agere，
# 但这两个根的 origin 里就写着 plicare 与 agere，是同一个根。
additions += [
    W("employ", "plic", "verb", "/ɪmˈplɔɪ/",
      "im-（in- 向内）+ ploy（折叠）→ implicare（把人卷进事里）→ 雇用、使用",
      "古法语 employer ← 拉丁语 implicare（卷入、缠进）← in＋plicare（折叠）",
      "to pay someone to work; to make use of something",
      "folding a person into the work so they are part of it – 把人折进这摊事里，成为其中一折",
      "名册上添了一个名字，从此这摊活里就有他一份",
      ["雇用", "使用", "employ"],
      ["The firm employs 200 people.", "She employed a clever trick."],
      ["hire", "use"], ["dismiss"],
      ["employee", "employer"],
      ["雇用：把人折进这摊事里、给他一份", "使用：把某物折进做法里派上用场"],
      "im-（向内）+ ploy（折叠）→ 把人折进事里"),
    W("employee", "plic", "noun", "/ɪmˈplɔɪiː/",
      "employ（雇用）+ -ee（受事者）→ 被折进这摊活里的那个人",
      "英语 employee，由 employ 加受事后缀 -ee 构成 ← 拉丁语 implicare",
      "a person who is paid to work for someone else",
      "the one folded in, who works and draws pay – 被折进来做活、按月领钱的那个",
      "工牌上印着号码，每月到日子就有一笔钱进账",
      ["雇员", "员工"],
      ["Every employee gets two weeks off.", "She is a long-serving employee."],
      ["worker", "staff"], ["employer"],
      ["employ", "employer"],
      ["雇员/员工：被折进这摊活里、按期领钱的那个人"],
      "employ（雇用）+ -ee（受事）→ 被折进来做活的人"),
    W("employer", "plic", "noun", "/ɪmˈplɔɪə(r)/",
      "employ（雇用）+ -er（施事者）→ 把人折进来的那一方",
      "英语 employer，由 employ 加施事后缀 -er 构成 ← 拉丁语 implicare",
      "a person or company that pays others to work",
      "the side that does the folding-in and pays for it – 把人折进来、并为此付钱的那一方",
      "签字那一栏是公司的印，钱从那边出",
      ["雇主", "用人单位"],
      ["Her employer gave her a raise.", "The employer must provide safety gear."],
      ["boss", "company"], ["employee"],
      ["employ", "employee"],
      ["雇主/用人单位：把人折进来做活、并为此付钱的那一方"],
      "employ（雇用）+ -er（施事）→ 把人折进来的那方"),
    W("exploit", "plic", "verb", "/ɪkˈsplɔɪt/",
      "ex-（出来）+ ploit（折叠）→ explicare（把折的摊开）→ 把用处榨出来 → 利用、开发",
      "古法语 esploitier（施行、获益）← 拉丁语 explicare（展开）← ex＋plicare（折叠）",
      "to use something fully for gain; to treat someone unfairly for profit",
      "unfolding a thing to get everything out of it – 把折着的摊开，把里头能取的都取出来",
      "那张折了几道的纸被完全摊平，背面的字也一并露了出来",
      ["利用", "开发", "剥削"],
      ["They exploit the mine for copper.", "Some firms exploit their workers."],
      ["use", "harness"], [],
      ["employ", "display"],
      ["利用/开发：把折着的摊开、取尽其中用处", "剥削：这种取尽用在人身上"],
      "ex-（出来）+ ploit（折叠）→ 摊开取尽其用"),
    W("embassy", "ag", "noun", "/ˈembəsi/",
      "ambactus（受派办事的人）→ 受派驻外办事的那个馆",
      "古法语 ambassee ← 意大利语 ambasciata ← 拉丁语 ambactus（受派之人）"
      "← 印欧 *ag-（推动、驱使）一支，与 act 同源远亲",
      "the official office of an ambassador in another country",
      "the house that stands in for one country inside another – 一国派在别国境内代它办事的那处馆",
      "门口挂着别国的旗，里头办的是那个国家的事",
      ["大使馆", "使节团"],
      ["He works at the British embassy.", "The embassy issued a warning."],
      ["mission", "office"], [],
      ["act", "action"],
      ["大使馆/使节团：一国派驻别国、代它办事的那处馆"],
      "ambactus（受派办事者）→ 派驻外国的那处馆"),
    W("essay", "ag", "noun", "/ˈeseɪ/",
      "ex-（出来）+ ag（驱动、称量）→ exagium（称重）→ 试着写出的一篇 → 短文",
      "古法语 essai（尝试、试验）← 晚期拉丁语 exagium（称量）← exigere（ex＋agere 推出、称量）",
      "a short piece of writing on one subject; an attempt",
      "the piece written as a weighing-out of one question – 就一个题目称量着写出的那一篇",
      "题目摆在纸头，底下一段段把想法称量着摆开",
      ["文章", "论文", "尝试"],
      ["She wrote an essay on climate.", "It was his first essay at farming."],
      ["article", "attempt"], [],
      ["exact", "act"],
      ["文章/论文：就一题称量着写出的那一篇", "尝试：同一个「试着称量」用作动作"],
      "ex-（出来）+ ag（称量）→ exagium → 试写的一篇"),
    W("exam", "ag", "noun", "/ɪɡˈzæm/",
      "examination 的截短 ← examen（秤舌）← ex＋ag（驱出、称量）→ 称量学识的那一场",
      "英语 exam 是 examination 的截短 ← 拉丁语 examen（天平的指针、称量）← exigere",
      "a formal test of knowledge or ability",
      "the occasion on which what one knows is weighed – 把人所知放上秤称一遍的那一场",
      "卷子发下来，会与不会当场就分出轻重",
      ["考试", "测验"],
      ["She passed the exam easily.", "The exam lasts two hours."],
      ["test", "check"], [],
      ["exact", "essay"],
      ["考试/测验：把人所知放上秤称量的那一场"],
      "examen（秤舌）← ex＋ag（称量）→ 称量学识的一场"),
    W("enable", "habere", "verb", "/ɪˈneɪbl/",
      "en-（使）+ able（拿得住）→ 使某人拿得住、办得成",
      "英语 enable，由 en-＋able 构成；able ← 拉丁语 habilis ← habere（拿住）",
      "to make it possible for someone to do something",
      "putting the thing within reach of a hand that could not hold it before – 让原先拿不住的那只手够得着、握得住",
      "垫脚的凳子搬来，本来伸手不及的那格就取到了",
      ["使能够", "使有可能"],
      ["The grant enabled her to study.", "This tool enables faster work."],
      ["allow", "permit"], ["prevent"],
      ["able", "ability"],
      ["使能够/使有可能：让原先拿不住的手够得着、握得住"],
      "en-（使）+ able（拿得住）→ 使其办得成"),
    W("disable", "habere", "verb", "/dɪsˈeɪbl/",
      "dis-（取消）+ able（拿得住）→ 使拿不住、使用不了",
      "英语 disable，由 dis-＋able 构成；able ← 拉丁语 habilis ← habere（拿住）",
      "to make someone unable to do something; to switch off a function",
      "taking away the grip that was there before – 把原先握得住的那份力撤掉",
      "闸一拉下来，方才还转着的机器立刻停住",
      ["使失能", "使残疾", "停用"],
      ["The injury disabled his right arm.", "Disable the alarm before entering."],
      ["weaken", "stop"], ["enable"],
      ["able", "enable"],
      ["使失能/使残疾：把原先握得住的那份力撤掉", "停用：把功能撤掉、使它用不了"],
      "dis-（取消）+ able（拿得住）→ 使拿不住"),
    W("endow", "dare", "verb", "/ɪnˈdaʊ/",
      "en-（使）+ dow（dare 给）→ 把一份给定在某人名下 → 捐赠、赋予",
      "盎格鲁法语 endouer ← en-＋古法语 douer ← 拉丁语 dotare（给嫁资）← dos ← dare（给）",
      "to give money or property to an institution; to give a quality naturally",
      "handing over a portion for good, not on loan – 交出去的那份是定给的，不是借的",
      "文书上写明这笔钱此后归学校，不再收回",
      ["捐赠", "赋予", "资助"],
      ["He endowed a scholarship fund.", "She is endowed with great patience."],
      ["donate", "grant"], [],
      ["data", "date"],
      ["捐赠/资助：把一份定给出去、不再收回", "赋予：天生就把某种性质给定在某人身上"],
      "en-（使）+ dow（给）→ 把一份定给出去"),
    W("dose", "dare", "noun", "/dəʊs/",
      "dosis（所给的一份）← didonai/dare（给）→ 一次给下的那个量",
      "法语 dose ← 晚期拉丁语 dosis ← 希腊语 dosis（给予、一份），与拉丁 dare 同出印欧 *do-（给）",
      "a measured amount of medicine taken at one time",
      "the one portion measured out to be handed over at a time – 量好、一次交出去的那一份",
      "药瓶盖里倒到那道刻线，一次就喝这么多",
      ["剂量", "一剂"],
      ["Take one dose every four hours.", "He got a high dose of radiation."],
      ["amount", "portion"], [],
      ["data", "date"],
      ["剂量/一剂：量好、一次给下的那一份"],
      "dosis（所给的一份）← 与 dare 同出印欧 *do-（给）"),
    W("elite", "legere", "noun", "/eɪˈliːt/",
      "e-（ex- 出来）+ lite（拣选）→ eligere（挑出来）→ 被挑出的那一小群",
      "法语 élite ← élire（挑选）← 拉丁语 eligere（选出）← ex＋legere（拣选）",
      "a small group with the most power or skill",
      "the few picked out of the many and set apart – 从众人里挑出来、单独放一处的那几个",
      "名单一层层筛下来，最后只剩最上面几个名字",
      ["精英", "上层集团"],
      ["The elite controlled the land.", "She joined an elite unit."],
      ["best", "top"], ["crowd"],
      ["collect", "collective"],
      ["精英/上层集团：从众人里挑出、单独放一处的那几个"],
      "e-（出来）+ lite（拣选）→ 挑出来的那一小群"),
    W("entire", "integer", "adjective", "/ɪnˈtaɪə(r)/",
      "integer（未经触碰的、完整的）→ 一点没缺的 → 全部的",
      "古法语 entier ← 拉丁语 integer（完整的、未动过的）← in-（不）＋tangere（触）",
      "whole; with no part missing",
      "the thing still as it came, nothing taken off – 还是原来那一整个，没被取走过任何一块",
      "整块蛋糕端上来，刀还没碰过它",
      ["整个的", "全部的", "完整的"],
      ["He ate the entire cake.", "The entire team agreed."],
      ["whole", "complete"], ["partial"],
      ["integrate", "integrity"],
      ["整个的/全部的/完整的：还是原来那一整个、没被取走任何一块"],
      "integer（未经触碰的完整）→ 一点没缺的"),
    W("ensure", "cura", "verb", "/ɪnˈʃʊə(r)/",
      "en-（使）+ sure（无忧）→ 把事办到没有可担心的余地 → 确保",
      "盎格鲁法语 enseurer ← en-＋seur（可靠的）← 拉丁语 securus（无忧的）← se-（无）＋cura（挂心）",
      "to make certain that something happens",
      "closing every gap until there is nothing left to worry about – 把每一处漏洞都堵上，没什么可担心了",
      "门窗一扇扇查过，回头再看一遍才走开",
      ["确保", "保证"],
      ["Please ensure the door is locked.", "This ensures a fair result."],
      ["guarantee", "secure"], [],
      ["cure", "accurate"],
      ["确保/保证：把每处漏洞都堵上、没什么可担心"],
      "en-（使）+ sure（无忧）→ 办到无可担心"),
    W("deliver", "liber", "verb", "/dɪˈlɪvə(r)/",
      "de-（彻底）+ liver（liberare 使自由）→ 把东西从手里放开交出去 → 递送",
      "古法语 delivrer ← 晚期拉丁语 deliberare（释放、交付）← de＋liberare（使自由）← liber（自由的）",
      "to take goods to someone; to give a speech; to help at a birth",
      "letting go of what you held so it passes on – 把攥着的松开，让它转到别处去",
      "包裹从手里递出去，签完字那人转身就走了",
      ["递送", "发表", "分娩"],
      ["They deliver bread every morning.", "She delivered a short speech."],
      ["send", "convey"], [],
      ["delivery", "liberal"],
      ["递送：把攥着的松开、让它转到别处", "发表：把话从口里放出去", "分娩：把胎儿从体内放出来"],
      "de-（彻底）+ liver（使自由）→ 从手里放开交出"),
    W("delivery", "liber", "noun", "/dɪˈlɪvəri/",
      "deliver（递送）+ -y → 递送这件事，或递到的那一批",
      "盎格鲁法语 delivree ← delivrer ← 晚期拉丁语 deliberare ← liber（自由的）",
      "the act of bringing goods; the way something is said; a birth",
      "the handing-over itself, and the load handed over – 交出这件事，及交出去的那一批",
      "清早那车停在门口，一箱箱往下卸",
      ["投递", "交付", "分娩"],
      ["The delivery arrived late.", "Her delivery of the speech was calm."],
      ["shipment", "transport"], [],
      ["deliver", "liberal"],
      ["投递/交付：把东西交出去这件事及那一批货", "分娩：把胎儿放出来这件事"],
      "deliver（递送）+ -y → 交出这件事及所交之物"),
    W("display", "plic", "verb", "/dɪˈspleɪ/",
      "dis-（分开）+ play（折叠）→ displicare（把折的展开）→ 摊开给人看",
      "古法语 despleier ← 拉丁语 displicare（展开）← dis＋plicare（折叠）",
      "to put something where people can see it; a show of something",
      "unfolding a thing so the whole of it faces out – 把折着的展开，整面朝外露出来",
      "折成一叠的图纸抖开铺平，整幅一次看全",
      ["展示", "陈列", "显示"],
      ["The museum displays old maps.", "The screen displays the time."],
      ["show", "exhibit"], ["hide"],
      ["employ", "exploit"],
      ["展示/陈列：把折着的展开、整面朝外给人看", "显示：屏幕把内容摊出来给人看"],
      "dis-（分开）+ play（折叠）→ 把折的展开给人看"),
    W("degree", "gradus", "noun", "/dɪˈɡriː/",
      "de-（往下）+ gree（gradus 一步）→ 一级一级的那个梯级 → 程度、学位",
      "古法语 degré ← 通俗拉丁语 degradus（阶级）← de＋gradus（一步、级）",
      "a level or amount on a scale; a qualification from a university",
      "one notch on a ladder of notches – 一格格刻度里的那一格",
      "温度计上一道道刻线，水银停在其中一道上",
      ["程度", "度数", "学位"],
      ["The water is at ninety degrees.", "She earned a degree in law."],
      ["level", "extent"], [],
      ["progress", "congress"],
      ["程度/度数：一格格刻度里的那一格", "学位：学业等级里评定到的那一级"],
      "de-（往下）+ gree（一步）→ 一级级刻度里的那一格"),
    W("desire", "sidus", "verb", "/dɪˈzaɪə(r)/",
      "de-（离开）+ sire（sidus 星）→ 抬头望星而盼 → 渴望",
      "古法语 desirer ← 拉丁语 desiderare（渴望，一说 de＋sidus 从星象盼求）← sidus（星）",
      "to want something very much",
      "the eyes lifted to something far off, wanting it down – 抬头望着远处那样东西，盼它落到手里",
      "夜里抬头望着那颗星看了很久，心里空着一处",
      ["渴望", "欲望", "想要"],
      ["He desired peace above all.", "She got everything she desired."],
      ["wish", "long"], [],
      ["consider", "considerable"],
      ["渴望/想要：抬头望着远处那样、盼它落到手里", "欲望：心里那处空着、要拿它来填的劲"],
      "de-（离开）+ sire（星）→ 望星而盼"),
    W("expire", "spirare", "verb", "/ɪkˈspaɪə(r)/",
      "ex-（出去）+ pire（spirare 呼吸）→ 气出去不再回来 → 到期、死",
      "拉丁语 exspirare（呼出、气绝）← ex＋spirare（呼吸）",
      "to come to an end; to stop being valid; to die",
      "the last breath going out with none coming back – 最后一口气出去，再没有吸进来的",
      "胸口起伏一次之后就平了下去，再没抬起来",
      ["到期", "期满", "去世"],
      ["My passport expires in May.", "He expired before dawn."],
      ["lapse", "end"], ["renew"],
      ["inspire", "inspiration"],
      ["到期/期满：效力像气一样出去不再回来", "去世：最后一口气出去不再吸进"],
      "ex-（出去）+ pire（呼吸）→ 气出去不再回来"),
    W("discreet", "cernere", "adjective", "/dɪˈskriːt/",
      "dis-（分开）+ creet（cernere 筛分）→ 分得清该说不该说 → 谨慎、不外传",
      "古法语 discret ← 拉丁语 discretus（分开的、有分辨的），discernere 的过去分词 ← dis＋cernere（筛分）",
      "careful not to say or do anything that causes trouble",
      "the one who sifts what may be said from what may not – 把能说的与不能说的筛开的那种人",
      "他知道内情，但话到嘴边只挑得出无关的几句",
      ["谨慎的", "不张扬的", "守口的"],
      ["Please be discreet about this.", "She made discreet inquiries."],
      ["careful", "cautious"], ["rash"],
      ["discern", "concern"],
      ["谨慎的/守口的：把能说与不能说筛开的那种", "不张扬的：把自己从人眼里筛开、不显出来"],
      "dis-（分开）+ creet（筛分）→ 分得清该说不该说"),
    W("discard", "charta", "verb", "/dɪsˈkɑːd/",
      "dis-（去掉）+ card（纸牌）→ 把手里那张牌打掉 → 丢弃",
      "英语 discard，由 dis-＋card 构成；card ← 拉丁语 charta（纸）",
      "to throw away something no longer wanted",
      "laying a card out of your hand and not taking it back – 把手里那张打出去，不再拿回",
      "他从手里抽出一张扣到桌边，那张就不算他的了",
      ["丢弃", "抛弃", "打出（牌）"],
      ["Discard the packaging first.", "She discarded two cards."],
      ["dump", "reject"], ["keep"],
      ["card", "chart"],
      ["丢弃/抛弃：把手里那张打出去、不再拿回", "打出（牌）：牌戏里这个动作的本义"],
      "dis-（去掉）+ card（纸牌）→ 把手里那张打掉"),
    W("exert", "serere", "verb", "/ɪɡˈzɜːt/",
      "ex-（出来）+ ert（serere 编连）→ exserere（抽出来）→ 把力使出来",
      "拉丁语 exserere（伸出、抽出）← ex＋serere（编连、串接）",
      "to use strength or influence to make something happen",
      "drawing the strand out of the weave and putting it to work – 把编在里头的那股抽出来使上",
      "攥紧的手往外一抽，绳上那股劲全使了出去",
      ["运用", "施加", "尽力"],
      ["He exerted all his strength.", "She exerts great influence here."],
      ["apply", "use"], [],
      ["insert", "assert"],
      ["运用/施加：把编在里头的那股力抽出来使上", "尽力：把自己那股全抽出来使"],
      "ex-（出来）+ ert（编连）→ 把里头那股抽出来使"),
    W("defy", "fidere", "verb", "/dɪˈfaɪ/",
      "de-（取消）+ fy（fidere 信托）→ 撤回信托、宣告不再服 → 违抗",
      "古法语 defier（挑战、宣告绝交）← 通俗拉丁语 disfidare ← dis＋fidus（可信的）← fidere（信托）",
      "to refuse to obey; to be impossible to explain",
      "taking back the trust once pledged and standing against it – 把当初许下的信托撤回，转身站到对面",
      "他把那份契约推回去，说往后不认这一条",
      ["违抗", "公然反抗", "使无法"],
      ["He defied the court order.", "The result defies explanation."],
      ["resist", "disobey"], ["obey"],
      ["confident", "faith"],
      ["违抗/公然反抗：撤回信托、转身站到对面", "使无法：某事顶住了解释，讲不通"],
      "de-（取消）+ fy（信托）→ 撤回信托、不再服"),
]

# ================= 组装 =================
words = []
roots = []
concepts = []
domain_add = {}
for fam in families:
    r = dict(fam["root"]); r["word_ids"] = []
    roots.append(r)
    concepts.append(fam["concept"])
    domain_add.setdefault(fam["domain"], []).append(r["id"])
    words.extend(fam["words"])
words.extend(additions)

# ---- 生成期自检 ----
for w in words:
    for zh in w["chinese"]:
        assert not (len(zh) >= 2 and zh in w["core_image"]), \
            f"Q12 泄题：{w['id']} 的 core_image 点名义项「{zh}」"
    if len(w["chinese"]) >= 2:
        assert w["semantic_expansions"], f"Q1：{w['id']} 多义却无 semantic_expansions"
    assert w["recall_hint"], f"Q12：{w['id']} 缺 recall_hint"
    assert len(w["examples"]) >= 2, f"{w['id']} 例句不足 2 条"
assert len({w["id"] for w in words}) == len(words), "词条 id 有重复"
assert len({r["id"] for r in roots}) == len(roots), "词根 id 有重复"
wid = {w["id"] for w in words}
clash = [r["id"] for r in roots if r["id"] in wid]
assert not clash, f"词根 id 与本批单词同名，会产生自环边：{clash}"

OUT.write_text(json.dumps({
    "roots": roots, "concepts": concepts,
    "domain_add": domain_add, "words": words,
}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"wrote {OUT}: {len(words)} 词（{len(words)-len(additions)} 族词 + "
      f"{len(additions)} 补词）, {len(roots)} 新词根")
